<?php

/**
 * @Project NUKEVIET 4.x
 * @Author VINADES.,JSC (contact@vinades.vn)
 * @Copyright (C) 2014 VINADES.,JSC. All rights reserved
 * @License GNU/GPL version 2 or any later version
 * @Createdate 2-10-2010 20:59
 */

if (! defined('NV_ADMIN')) {
    die('Stop!!!');
}

/**
 * Note:
 * 	- Module var is: $lang, $module_file, $module_data, $module_upload, $module_theme, $module_name
 * 	- Accept global var: $db, $db_config, $global_config
 */

global $op;

$result = $db->query("SHOW TABLE STATUS LIKE '" . $db_config['prefix'] . "\_" . $module_data . "\_rows'");
$num_table = intval($result->rowCount());

// Truncate data
if ($num_table == 1 and $op != 'setup') {
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_block");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_block_cat");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_catalogs");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_rows");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_units");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_tabs");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_tags_vi");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_tags_id_vi");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_group");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_group_cateid");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_group_items");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_warehouse");
    $db->query("TRUNCATE " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs");
}

if ($num_table == 1) {
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block (bid, id, weight) VALUES('1', '11', '5');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block (bid, id, weight) VALUES('1', '10', '4');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block (bid, id, weight) VALUES('1', '9', '3');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block (bid, id, weight) VALUES('1', '6', '2');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block (bid, id, weight) VALUES('1', '5', '1');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block (bid, id, weight) VALUES('2', '4', '4');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block (bid, id, weight) VALUES('2', '3', '3');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block (bid, id, weight) VALUES('2', '2', '2');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block (bid, id, weight) VALUES('2', '1', '1');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block_cat (bid, adddefault, image, weight, add_time, edit_time, vi_title, vi_alias, vi_description, vi_keywords) VALUES('1', '0', '', '1', '1433298294', '1433298294', 'Sản phẩm bán chạy', 'San-pham-ban-chay', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_block_cat (bid, adddefault, image, weight, add_time, edit_time, vi_title, vi_alias, vi_description, vi_keywords) VALUES('2', '0', '', '2', '1433298325', '1433298325', 'Sản phẩm hot', 'San-pham-hot', '', '');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('2', '0', '', '1', '1', '0', 'viewcat_page_list', '4', '6,7,8,9', '1', '4', '7', '1', '', '', '0', '', '1432362728', '1432362803', '6', '0', '0', '0', 'Váy', 'Váy', 'Vay-nu', '', '', 'váy, vay');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('3', '0', '', '2', '6', '0', 'viewcat_page_list', '4', '13,14,15,16', '1', '4', '7', '1', '', '', '0', '', '1432362789', '1432362789', '6', '0', '0', '0', 'Giày dép', 'Giày dép', 'Giay-dep', '', '', 'giay, dep, giày, dép');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('4', '0', '', '3', '11', '0', 'viewcat_page_list', '3', '10,11,12', '1', '4', '7', '1', '', '', '0', '', '1432362835', '1432364806', '6', '0', '0', '0', 'Áo', 'Áo', 'Ao', '', '', 'áo, ao');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('5', '0', '', '4', '15', '0', 'viewcat_page_list', '5', '18,19,20,21,22', '1', '4', '7', '1', '', '', '0', '', '1432362887', '1432362887', '6', '0', '0', '0', 'Phụ kiện', 'Phụ kiện', 'Phu-kien', '', '', 'Phụ kiện, Phu kien, kiện, kien, phu kien');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('6', '2', '', '1', '2', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432364675', '1432364675', '6', '0', '0', '0', 'váy dài', 'váy dài', 'vay-dai', '', '', 'váy dài, dài, vay dai');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('7', '2', '', '2', '3', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432364695', '1432364695', '6', '0', '0', '0', 'váy ngắn', 'váy ngắn', 'vay-ngan', '', '', 'váy ngắn, vay ngan');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('8', '2', '', '3', '4', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432364752', '1432364752', '6', '0', '0', '0', 'đầm maxi', 'đầm maxi', 'dam-maxi', '', '', 'đầm, maxi, Maxi, đầm maxi, Đầm maxi');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('9', '2', '', '4', '5', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432364786', '1432364786', '6', '0', '0', '0', 'Váy chữ A', 'Váy chữ A', 'Vay-chu-A', '', '', 'Váy chữ A, váy chữ a');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('10', '4', '', '1', '12', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432364825', '1432364863', '6', '0', '0', '0', 'Áo sơmi', 'Áo sơmi', 'Ao-somi', '', '', 'Áo sơmi,, sơmi. áo');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('11', '4', '', '2', '13', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432364880', '1432364880', '6', '0', '0', '0', 'Áo phông', 'Áo phông', 'Ao-phong', '', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('12', '4', '', '3', '14', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432364936', '1432364936', '6', '0', '0', '0', 'Áo dáng dài', 'Áo dáng dài', 'Ao-dang-dai', '', '', 'Áo dáng dài, áo');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('13', '3', '', '1', '7', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432364976', '1432364976', '6', '0', '0', '0', 'Giày cao gót', 'Giày cao gót', 'Giay-cao-got', '', '', 'Giày cao gót, cao gót, cao got');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('14', '3', '', '2', '8', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432365033', '1432365033', '6', '0', '0', '0', 'Giày sandal', 'Giày sandal', 'Giay-sandal', '', '', 'sandal, Sandal, giày, giày sandal');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('15', '3', '', '3', '9', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432365081', '1432365081', '6', '0', '0', '0', 'Giày búp bê', 'Giày búp bê', 'Giay-bup-be', '', '', 'giày búp bê, Giày búp bê, giay bup be, Giay bup be, búp bê, bup be');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('16', '3', '', '4', '10', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432365108', '1432365108', '6', '0', '0', '0', 'Giày vải', 'Giày vải', 'Giay-vai', '', '', 'vải, giày vải, giay vai');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('19', '5', '', '2', '17', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432365211', '1432365211', '6', '0', '0', '0', 'Lắc tay', 'Lắc tay', 'Lac-tay', '', '', 'Lắc tay. lac tay, lắc');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('18', '5', '', '1', '16', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432365185', '1432365185', '6', '0', '0', '0', 'Vòng cổ', 'Vòng cổ', 'Phu-kien-Vong-co', '', '', 'vòng cổ, Vòng cổ, vong co');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('20', '5', '', '3', '18', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432365242', '1432365242', '6', '0', '0', '0', 'Thắt lưng', 'Thắt lưng', 'That-lung', '', '', 'Thắt lưng, that lung, thắt lưng');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('21', '5', '', '4', '19', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432365281', '1432365281', '6', '0', '0', '0', 'Đồng hồ', 'Đồng hồ', 'Dong-ho', '', '', 'Đồng hồ, hồ, dong ho');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_catalogs (catid, parentid, image, weight, sort, lev, viewcat, numsubcat, subcatid, inhome, numlinks, newday, typeprice, form, group_price, viewdescriptionhtml, admins, add_time, edit_time, groups_view, cat_allow_point, cat_number_point, cat_number_product, vi_title, vi_title_custom, vi_alias, vi_description, vi_descriptionhtml, vi_keywords) VALUES('22', '5', '', '5', '20', '1', 'viewcat_page_list', '0', '', '1', '4', '7', '1', '', '', '0', '', '1432365303', '1432365303', '6', '0', '0', '0', 'Ví nữ', 'Ví nữ', 'Vi-nu', '', '', 'ví nữ, ví');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('1', '6', '1', '1432363521', '1432365563', '1', '1432363521', '0', '2', 'V01', '19', '100000', '', 'VND', '1', '20', 'g', '0', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', 'Váy Maxi sang trọng', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '11', '0', '0', '1', '1', 'Đầm Maxi sang trọng', 'Dam-Maxi-sang-trong', 'Đầm maxi thời trang', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('2', '6', '1', '1432365534', '1432365970', '1', '1432365534', '0', '2', 'V02', '50', '100000', '', 'VND', '1', '250', 'g', '0', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', '', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '1', '0', '0', '0', '1', 'Đầm maxi họa tiết', 'Dam-maxi-hoa-tiet', 'đầm maxi sang trọng', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('3', '7', '1', '1432366714', '1432366740', '1', '1432366714', '0', '2', 'V03', '14', '50000', '', 'VND', '1', '250', 'g', '0', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', 'Chân Váy Công Sở', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '4', '0', '0', '1', '1', 'Chân Váy Công Sở', 'Chan-Vay-Cong-So', 'chân váy công sở', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('4', '7', '1', '1432367089', '1432367089', '1', '1432367089', '0', '2', 'S000004', '17', '50000', '', 'VND', '1', '300', 'g', '0', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', 'chân váy caro', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '4', '0', '0', '3', '1', 'Chân váy caro', 'Chan-vay-caro', 'chân váy caro', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('5', '10', '1', '1432367366', '1432367366', '1', '1432367366', '0', '2', 'S000005', '30', '0', '', 'VND', '1', '220', 'g', '0', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', 'áo somi lụa đẹp', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '0', '0', '0', '0', '1', 'Áo sơmi lụa', 'Ao-somi-lua', 'áo somi lụa đẹp', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('6', '10', '1', '1432367846', '1432370007', '1', '1432367846', '0', '2', 'S000006', '15', '0', '', 'VND', '1', '300', 'g', '0', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', '', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '8', '0', '0', '0', '1', 'Áo sơ mi voan phối tay ren', 'Ao-so-mi-voan-phoi-tay-ren', '<h1><span style=\"font-size:14px;\">Áo sơ mi voan</span></h1>', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('8', '11', '1', '1432605984', '1432605984', '1', '1432605984', '0', '2', 'S000008', '15', '120000', '', 'VND', '1', '200', 'g', '0', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', 'áo thun nữ', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '1', '0', '0', '0', '1', 'áo thun nữ họa tiết độc đáo', 'ao-thun-nu-hoa-tiet-doc-dao', 'áo thun nữ họa tiết độc đáo', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('9', '13', '1', '1432606317', '1432629809', '1', '1432606317', '0', '2', 'S000009', '10', '100000', '', 'VND', '1', '500', 'g', '1', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', 'Giày da nữ gót vuông', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '1', '0', '0', '0', '1', 'Giày da nữ gót vuông', 'Giay-da-nu-got-vuong', 'Giày da nữ gót vuông', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('10', '13', '1', '1432606522', '1432629789', '1', '1432606522', '0', '2', 'S000010', '10', '100000', '', 'VND', '2', '350', 'g', '2', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', 'Giày cao gót mũi nhọn màu hồng', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '1', '0', '0', '0', '1', 'Giày cao gót mũi nhọn màu hồng be quý phái', 'Giay-cao-got-mui-nhon-mau-hong-be-quy-phai', 'Giày cao gót mũi nhọn màu hồng be quý phái', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('7', '11', '1', '1432369124', '1432369433', '1', '1432369124', '0', '2', 'S000007', '50', '120000', '', 'VND', '1', '150', 'g', '0', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', '', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '2', '0', '0', '0', '1', 'áo thun nữ', 'ao-thun-nu', 'áo thun nữ', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_rows (id, listcatid, user_id, addtime, edittime, status, publtime, exptime, archive, product_code, product_number, product_price, price_config, money_unit, product_unit, product_weight, weight_unit, discount_id, homeimgfile, homeimgthumb, homeimgalt, otherimage, imgposition, copyright, gift_from, gift_to, inhome, allowed_comm, allowed_rating, ratingdetail, allowed_send, allowed_print, allowed_save, hitstotal, hitscm, hitslm, num_sell, showprice, vi_title, vi_alias, vi_hometext, vi_bodytext, vi_gift_content, vi_address) VALUES('11', '15', '1', '1432607113', '1435376866', '1', '1432607113', '0', '2', 'S000011', '20', '100000', '', 'VND', '2', '250', 'g', '0', '2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg', '1', 'GIÀY BÚP BÊ NGÔI SAO NHẬP KHẨU', '', '0', '0', '0', '0', '1', '4', '1', '0', '1', '1', '1', '2', '0', '0', '0', '1', 'GIÀY BÚP BÊ NGÔI SAO NHẬP KHẨU', 'GIAY-BUP-BE-NGOI-SAO-NHAP-KHAU', 'GIÀY BÚP BÊ NGÔI SAO NHẬP KHẨU', 'Sản phẩm thời trang<br  /> <div style=\"text-align:center\"><img alt=\"giay bup be ngoi sao nhap khau\" height=\"800\" src=\"/uploads/shops/2015_05/giay-bup-be-ngoi-sao-nhap-khau.jpg\" width=\"800\" /></div> ', '', '');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_units (id, vi_title, vi_note) VALUES('1', 'cái', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_units (id, vi_title, vi_note) VALUES('2', 'đôi', '');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tabs (id, icon, content, weight, active, vi_title) VALUES('1', '', 'content_detail', '1', '1', 'Chi tiết sản phẩm');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tabs (id, icon, content, weight, active, vi_title) VALUES('2', '', 'content_comments', '2', '1', 'Bình luận');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tabs (id, icon, content, weight, active, vi_title) VALUES('3', '', 'content_rate', '3', '1', 'Đánh giá');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_vi (tid, numpro, alias, image, description, keywords) VALUES('1', '1', 'thời-trang', '', '', 'thời trang');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_vi (tid, numpro, alias, image, description, keywords) VALUES('2', '1', 'sang-trọng', '', '', 'sang trọng');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_vi (tid, numpro, alias, image, description, keywords) VALUES('3', '1', 'phù-hợp', '', '', 'phù hợp');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_vi (tid, numpro, alias, image, description, keywords) VALUES('4', '1', 'đi-chơi', '', '', 'đi chơi');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_vi (tid, numpro, alias, image, description, keywords) VALUES('5', '1', 'áo-sơ-mi', '', '', 'áo sơ mi');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_vi (tid, numpro, alias, image, description, keywords) VALUES('6', '1', 'mũi-nhọn', '', '', 'mũi nhọn');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_vi (tid, numpro, alias, image, description, keywords) VALUES('7', '1', 'búp-bê', '', '', 'búp bê');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_id_vi (id, tid, keyword) VALUES('1', '1', 'thời trang');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_id_vi (id, tid, keyword) VALUES('1', '2', 'sang trọng');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_id_vi (id, tid, keyword) VALUES('1', '3', 'phù hợp');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_id_vi (id, tid, keyword) VALUES('1', '4', 'đi chơi');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_id_vi (id, tid, keyword) VALUES('6', '5', 'áo sơ mi');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_id_vi (id, tid, keyword) VALUES('10', '6', 'mũi nhọn');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_tags_id_vi (id, tid, keyword) VALUES('11', '7', 'búp bê');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('1', '0', '', '1', '1', '0', 'viewcat_page_list', '6', '6,7,8,9,10,11', '1', '0', '1432623061', '1432623061', '0', '1', '0', 'Thương hiệu', 'Thuong-hieu', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('2', '0', '', '2', '8', '0', 'viewcat_page_list', '12', '12,13,15,16,17,18,19,20,21,22,23,24', '1', '0', '1432623083', '1432623083', '0', '1', '0', 'Màu sắc', 'Mau-sac', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('3', '0', '', '3', '21', '0', 'viewcat_page_list', '15', '25,26,27,28,29,30,31,32,33,34,35,36,37,38,39', '1', '0', '1432623101', '1432623101', '0', '1', '0', 'Kích thước', 'Kich-thuoc', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('4', '0', '', '4', '37', '0', 'viewcat_page_list', '8', '40,41,42,43,44,45,46,47', '1', '0', '1432623118', '1432623118', '0', '1', '0', 'Chất liệu', 'Chat-lieu', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('5', '0', '', '5', '46', '0', 'viewcat_page_list', '10', '48,49,50,51,52,53,54,55,56,57', '1', '0', '1432623133', '1432623133', '0', '1', '0', 'Xuất xứ', 'Xuat-xu', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('6', '1', '', '1', '2', '1', 'viewcat_page_list', '0', '', '1', '0', '1432626862', '1432626862', '0', '1', '0', 'Việt Tiến', 'Viet-Tien', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('7', '1', '', '2', '3', '1', 'viewcat_page_list', '0', '', '1', '0', '1432626882', '1432626882', '3', '1', '0', 'ZARA', 'ZARA', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('8', '1', '', '3', '4', '1', 'viewcat_page_list', '0', '', '1', '0', '1432626899', '1432626899', '0', '1', '0', 'MATTANA', 'MATTANA', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('9', '1', '', '4', '5', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627013', '1432627013', '0', '1', '0', 'KELVIN', 'KELVIN', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('10', '1', '', '5', '6', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627027', '1432627027', '0', '1', '0', 'THÁI TUẤN', 'THAI-TUAN', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('11', '1', '', '6', '7', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627053', '1432627053', '0', '1', '0', 'VICTORIA SECRECT', 'VICTORIA-SECRECT', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('12', '2', '', '1', '9', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627064', '1432627064', '0', '1', '0', 'ĐỎ', 'DO', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('13', '2', '', '2', '10', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627070', '1432627070', '0', '1', '0', 'VÀNG', 'VANG', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('16', '2', '', '4', '12', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627102', '1432627102', '1', '1', '0', 'HỒNG PHẤN', 'HONG-PHAN', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('15', '2', '', '3', '11', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627095', '1432627095', '0', '1', '0', 'XANH NGỌC', 'XANH-NGOC', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('17', '2', '', '5', '13', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627107', '1432627107', '0', '1', '0', 'XANH RÊU', 'XANH-REU', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('18', '2', '', '6', '14', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627112', '1432627112', '0', '1', '0', 'TÍM', 'TIM', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('19', '2', '', '7', '15', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627123', '1432627123', '0', '1', '0', 'XÁM', 'XAM', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('20', '2', '', '8', '16', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627135', '1432627135', '0', '1', '0', 'XANH NƯỚC BIỂN', 'XANH-NUOC-BIEN', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('21', '2', '', '9', '17', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627148', '1432627148', '0', '1', '0', 'CAM', 'CAM', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('22', '2', '', '10', '18', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627153', '1432627153', '0', '1', '0', 'BẠC', 'BAC', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('23', '2', '', '11', '19', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627160', '1432627160', '0', '1', '0', 'MÀU DA', 'MAU-DA', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('24', '2', '', '12', '20', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627182', '1432627182', '2', '1', '0', 'ĐEN', 'DEN', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('25', '3', '', '1', '22', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627201', '1432627201', '0', '1', '0', 'F', 'F', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('26', '3', '', '2', '23', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627210', '1432627210', '0', '1', '0', 'L', 'L', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('27', '3', '', '3', '24', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627215', '1432627215', '0', '1', '0', 'M', 'M', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('28', '3', '', '4', '25', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627219', '1432627219', '0', '1', '0', 'S', 'S', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('29', '3', '', '5', '26', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627223', '1432627223', '0', '1', '0', 'XL', 'XL', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('30', '3', '', '6', '27', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627241', '1432627241', '0', '1', '0', 'XXL', 'XXL', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('31', '3', '', '7', '28', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627250', '1432627250', '0', '1', '0', 'XXXL', 'XXXL', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('32', '3', '', '8', '29', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627259', '1432627259', '2', '1', '0', '35', '35', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('33', '3', '', '9', '30', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627264', '1432627264', '2', '1', '0', '36', '36', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('34', '3', '', '10', '31', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627269', '1432627269', '2', '1', '0', '37', '37', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('35', '3', '', '11', '32', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627274', '1432627274', '3', '1', '0', '38', '38', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('36', '3', '', '12', '33', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627279', '1432627279', '0', '1', '0', '39', '39', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('37', '3', '', '13', '34', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627284', '1432627284', '0', '1', '0', '40', '40', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('38', '3', '', '14', '35', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627291', '1432627291', '0', '1', '0', '41', '41', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('39', '3', '', '15', '36', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627296', '1432627296', '0', '1', '0', '42', '42', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('40', '4', '', '1', '38', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627339', '1432627339', '0', '1', '0', 'COTTON', 'COTTON', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('41', '4', '', '2', '39', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627346', '1432627346', '0', '1', '0', 'DẠ', 'DA', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('42', '4', '', '3', '40', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627364', '1432627364', '0', '1', '0', 'JEANS', 'JEANS', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('43', '4', '', '4', '41', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627369', '1432627369', '0', '1', '0', 'BÒ', 'BO', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('44', '4', '', '5', '42', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627378', '1432627378', '0', '1', '0', 'LANH', 'LANH', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('45', '4', '', '6', '43', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627385', '1432627385', '0', '1', '0', 'TƠ TẰM', 'TO-TAM', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('46', '4', '', '7', '44', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627399', '1432627399', '0', '1', '0', 'THUN', 'THUN', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('47', '4', '', '8', '45', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627407', '1432627407', '0', '1', '0', 'LỤA', 'LUA', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('48', '5', '', '1', '47', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627418', '1432627418', '0', '1', '0', 'VIỆT NAM', 'VIET-NAM', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('49', '5', '', '2', '48', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627425', '1432627425', '0', '1', '0', 'HÀN QUỐC', 'HAN-QUOC', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('50', '5', '', '3', '49', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627519', '1432627519', '0', '1', '0', 'ĐỨC', 'DUC', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('51', '5', '', '4', '50', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627528', '1432627528', '1', '1', '0', 'NHẬT BẢN', 'NHAT-BAN', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('52', '5', '', '5', '51', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627541', '1432627541', '0', '1', '0', 'THÁI LAN', 'THAI-LAN', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('53', '5', '', '6', '52', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627553', '1432627553', '1', '1', '0', 'HONGKONG', 'HONGKONG', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('54', '5', '', '7', '53', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627565', '1432627565', '0', '1', '0', 'TRUNG QUỐC', 'TRUNG-QUOC', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('55', '5', '', '8', '54', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627573', '1432627573', '0', '1', '0', 'PHÁP', 'PHAP', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('56', '5', '', '9', '55', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627579', '1432627579', '0', '1', '0', 'ANH', 'ANH', '', '');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group (groupid, parentid, image, weight, sort, lev, viewgroup, numsubgroup, subgroupid, inhome, indetail, add_time, edit_time, numpro, in_order, is_require, vi_title, vi_alias, vi_description, vi_keywords) VALUES('57', '5', '', '10', '56', '1', 'viewcat_page_list', '0', '', '1', '0', '1432627617', '1432627617', '0', '1', '0', 'AUSTRALIA', 'AUSTRALIA', '', '');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('1', '2');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('1', '3');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('1', '4');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('1', '5');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('2', '2');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('2', '3');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('2', '4');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('2', '5');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('3', '2');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('3', '3');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('3', '4');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('3', '5');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('4', '2');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('4', '3');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('4', '4');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('4', '5');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('5', '2');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('5', '3');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('5', '4');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_cateid (groupid, cateid) VALUES('5', '5');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('9', '7');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('9', '24');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('9', '32');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('9', '33');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('9', '34');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('9', '35');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('9', '53');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('10', '7');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('10', '16');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('10', '32');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('10', '33');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('10', '34');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('10', '35');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('10', '51');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('11', '7');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('11', '24');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_group_items (pro_id, group_id) VALUES('11', '35');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('1', 'Nhập kho ngày 23/05/2015', '', '1', '1432364016');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('2', 'Nhập kho ngày 23/05/2015', '', '1', '1432365552');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('3', 'Nhập kho ngày 23/05/2015', '', '1', '1432366753');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('4', 'Nhập kho ngày 23/05/2015', '', '1', '1432367106');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('5', 'Nhập kho ngày 23/05/2015', '', '1', '1432367387');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('6', 'Nhập kho ngày 23/05/2015', '', '1', '1432367857');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('7', 'Nhập kho ngày 23/05/2015', '', '1', '1432369139');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('8', 'Nhập kho ngày 26/05/2015', '', '1', '1432608794');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('9', 'Nhập kho ngày 26/05/2015', '', '1', '1432608805');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('10', 'Nhập kho ngày 26/05/2015', '', '1', '1432608819');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse (wid, title, note, user_id, addtime) VALUES('11', 'Nhập kho ngày 26/05/2015', '', '1', '1432608835');");

    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('1', '1', '1', '20', '150000', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('2', '2', '2', '50', '250000', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('3', '3', '3', '15', '70000', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('4', '4', '4', '20', '120000', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('5', '5', '5', '30', '120000', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('6', '6', '6', '15', '180000', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('7', '7', '7', '50', '50000', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('8', '8', '11', '20', '80', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('9', '9', '10', '10', '180', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('10', '10', '9', '10', '150', 'VND');");
    $db->query("INSERT INTO " . $db_config['prefix'] . "_" . $module_data . "_warehouse_logs (logid, wid, pro_id, quantity, price, money_unit) VALUES('11', '11', '8', '15', '50000', 'VND');");
}