/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
 */

CKEDITOR.dialog.add("image2",function(l){function C(){var a=this.getValue().match(D);(a=!(!a||0===parseInt(a[1],10)))||alert(c["invalid"+CKEDITOR.tools.capitalize(this.id)]);return a}function N(){function a(a,b){d.push(k.once(a,function(a){for(var k;k=d.pop();)k.removeListener();b(a)}))}var k=s.createElement("img"),d=[];return function(d,b,c){a("load",function(){var a=E(k);b.call(c,k,a.width,a.height)});a("error",function(){b(null)});a("abort",function(){b(null)});k.setAttribute("src",(w.baseHref||
"")+d+"?"+Math.random().toString(16).substring(2))}}function F(){var a=this.getValue();t(!1);a!==x.data.src?(G(a,function(a,d,b){t(!0);if(!a)return m(!1);g.setValue(d);h.setValue(b);u=d;v=b;m(H.checkHasNaturalRatio(a))}),n=!0):n?(t(!0),g.setValue(p),h.setValue(q),n=!1):t(!0)}function I(){if(e){var a=this.getValue();if(a&&(a.match(D)||m(!1),"0"!==a)){var b="width"==this.id,d=p||u,c=q||v,a=b?Math.round(a/d*c):Math.round(a/c*d);isNaN(a)||(b?h:g).setValue(a)}}}function m(a){if(f){if("boolean"==typeof a){if(y)return;
e=a}else a=g.getValue(),y=!0,(e=!e)&&a&&(a*=q/p,isNaN(a)||h.setValue(Math.round(a)));f[e?"removeClass":"addClass"]("cke_btn_unlocked");f.setAttribute("aria-checked",e);CKEDITOR.env.hc&&f.getChild(0).setHtml(e?CKEDITOR.env.ie?"\u25a0":"\u25a3":CKEDITOR.env.ie?"\u25a1":"\u25a2")}}function t(a){a=a?"enable":"disable";g[a]();h[a]()}var D=/(^\s*(\d+)(px)?\s*$)|^$/i,J=CKEDITOR.tools.getNextId(),K=CKEDITOR.tools.getNextId(),b=l.lang.image2,c=l.lang.common,O=(new CKEDITOR.template('<div><a href="javascript:void(0)" tabindex="-1" title="'+
b.lockRatio+'" class="cke_btn_locked" id="{lockButtonId}" role="checkbox"><span class="cke_icon"></span><span class="cke_label">'+b.lockRatio+'</span></a><a href="javascript:void(0)" tabindex="-1" title="'+b.resetSize+'" class="cke_btn_reset" id="{resetButtonId}" role="button"><span class="cke_label">'+b.resetSize+"</span></a></div>")).output({lockButtonId:J,resetButtonId:K}),H=CKEDITOR.plugins.image2,w=l.config,z=l.widgets.registered.image.features,E=H.getNatural,s,x,L,G,p,q,u,v,n,e,y,f,r,g,h,A,
B=!(!w.filebrowserImageBrowseUrl&&!w.filebrowserBrowseUrl),M=[{id:"src",type:"text",label:c.url,onKeyup:F,onChange:F,setup:function(a){this.setValue(a.data.src)},commit:function(a){a.setData("src",this.getValue())},validate:CKEDITOR.dialog.validate.notEmpty(b.urlMissing)}];B&&M.push({type:"button",id:"browse",style:"display:inline-block;margin-top:14px;",align:"center",label:l.lang.common.browseServer,hidden:!0,filebrowser:"info:src"});return{title:b.title,minWidth:250,minHeight:100,onLoad:function(){s=
this._.element.getDocument();G=N()},onShow:function(){x=this.widget;L=x.parts.image;n=y=e=!1;A=E(L);u=p=A.width;v=q=A.height},contents:[{id:"info",label:b.infoTab,elements:[{type:"vbox",padding:0,children:[{type:"hbox",widths:["100%"],children:M}]},{id:"alt",type:"text",label:b.alt,setup:function(a){this.setValue(a.data.alt)},commit:function(a){a.setData("alt",this.getValue())}},{type:"hbox",widths:["25%","25%","50%"],requiredContent:z.dimension.requiredContent,children:[{type:"text",width:"45px",
id:"width",label:c.width,validate:C,onKeyUp:I,onLoad:function(){g=this},setup:function(a){this.setValue(a.data.width)},commit:function(a){a.setData("width",this.getValue())}},{type:"text",id:"height",width:"45px",label:c.height,validate:C,onKeyUp:I,onLoad:function(){h=this},setup:function(a){this.setValue(a.data.height)},commit:function(a){a.setData("height",this.getValue())}},{id:"lock",type:"html",style:"margin-top:18px;width:40px;height:20px;",onLoad:function(){function a(a){a.on("mouseover",function(){this.addClass("cke_btn_over")},
a);a.on("mouseout",function(){this.removeClass("cke_btn_over")},a)}var b=this.getDialog();f=s.getById(J);r=s.getById(K);f&&(b.addFocusable(f,4+B),f.on("click",function(a){m();a.data&&a.data.preventDefault()},this.getDialog()),a(f));r&&(b.addFocusable(r,5+B),r.on("click",function(a){n?(g.setValue(u),h.setValue(v)):(g.setValue(p),h.setValue(q));a.data&&a.data.preventDefault()},this),a(r))},setup:function(a){m(a.data.lock)},commit:function(a){a.setData("lock",e)},html:O}]},{type:"hbox",id:"alignment",
requiredContent:z.align.requiredContent,children:[{id:"align",type:"radio",items:[[c.alignNone,"none"],[c.alignLeft,"left"],[c.alignCenter,"center"],[c.alignRight,"right"]],label:c.align,setup:function(a){this.setValue(a.data.align)},commit:function(a){a.setData("align",this.getValue())}}]},{id:"hasCaption",type:"checkbox",label:b.captioned,requiredContent:z.caption.requiredContent,setup:function(a){""==a.data.src&&(a.data.hasCaption=!0);this.setValue(a.data.hasCaption)},commit:function(a){a.setData("hasCaption",
this.getValue());this.getValue()&&""!=a.data.alt&&(l.lang.image2.captionPlaceholder=a.data.alt)}}]},{id:"Upload",hidden:!0,filebrowser:"uploadButton",label:b.uploadTab,elements:[{type:"file",id:"upload",label:b.btnUpload,style:"height:40px"},{type:"fileButton",id:"uploadButton",filebrowser:"info:src",label:b.btnUpload,"for":["Upload","upload"]}]}]}});