{if $UNOFFICIAL_MODE}
<div class="alert alert-warning"><i class="fa-solid fa-triangle-exclamation"></i> {$LANG->getModule('is_unofficial_mode')}.</div>
{/if}
<form action="#" id="checklang">
    <label for="lang" class="form-label">{$LANG->getModule('select_lang_des')}</label>
    <select class="form-select" id="lang" data-toggle="selectLang" data-other-url="http://translate.nukeviet.vn/en/translate/download/">
        {foreach from=$LANGS key=lang item=langname}
        <option value="{$smarty.const.NV_BASE_SITEURL}install/index.php?{$smarty.const.NV_LANG_VARIABLE}={$lang}&amp;step=1&amp;t={$smarty.const.NV_CURRENTTIME}"{if $lang eq $smarty.const.NV_LANG_DATA} selected{/if}>{$langname}</option>
        {/foreach}
        <option value="other">Other Language</option>
    </select>
</form>
<div class="mt-4">
    <h3 class="h6 text-dark"><i class="fa-solid fa-heart text-danger"></i> {$LANG->getModule('thanks')}</h3>
    <p>{$LANG->getModule('thanks_text')}</p>
    <div class="install-thanks">
        <p class="mb-1 fw-medium">{$LANG->getModule('thanks_list_member_all')}</p>
        <p>VINADES.,JSC, <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao</a>, <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99</a>, <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen</a>, <a target="_blank" rel="noopener" href="https://github.com/mynukeviet">mynukeviet</a>, <a target="_blank" rel="noopener" href="https://github.com/tdfoss">tdfoss</a>, <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung</a>, khoaij123, dat.huynh, dinhpc86 at gmail.com, <a target="_blank" rel="noopener" href="https://github.com/anhyeuviolet">anhyeuviolet</a>, <a target="_blank" rel="noopener" href="https://github.com/trinhthinhhp">trinhthinhhp</a>, nguyenhung2904 at gmail.com, <a target="_blank" rel="noopener" href="https://github.com/htuyen9x">htuyen9x</a>, <a target="_blank" rel="noopener" href="https://github.com/dangdlinhtu">dangdlinhtu</a>, <a target="_blank" rel="noopener" href="https://github.com/thangbv">thangbv</a>, trankhuyen81 at gmail.com, <a target="_blank" rel="noopener" href="https://github.com/thuvp1995">thuvp1995</a>, <a target="_blank" rel="noopener" href="https://github.com/PhamQuocTien132">PhamQuocTien132</a>, mabubeo1990 at gmail.com, <a target="_blank" rel="noopener" href="https://github.com/phongaz">phongaz</a>, tamahari at gmail.com, <a target="_blank" rel="noopener" href="https://github.com/ngocphan12031995">ngocphan12031995</a>, hungtmit at gmail.com, <a target="_blank" rel="noopener" href="https://github.com/tkhuyenbk">tkhuyenbk</a>, <a target="_blank" rel="noopener" href="https://github.com/webvang">webvang</a>, <a target="_blank" rel="noopener" href="https://github.com/hiidemo">hiidemo</a>, <a target="_blank" rel="noopener" href="https://github.com/thethao">thethao</a>, <a target="_blank" rel="noopener" href="https://github.com/tuanta">tuanta</a>, <a target="_blank" rel="noopener" href="https://github.com/duyetdev">duyetdev</a>, ledinhhung87 at gmail.com, mtmost.com at gmail.com, <a target="_blank" rel="noopener" href="https://github.com/truongdacngoc1993">truongdacngoc1993</a>, <a target="_blank" rel="noopener" href="https://github.com/ThinhNguyenVB">ThinhNguyenVB</a>, Hoàng Tuyên at VINADES.,JSC</p>
        <button class="btn btn-sm btn-link px-0" type="button" data-bs-toggle="collapse" data-bs-target="#thanks-versions" aria-expanded="false" aria-controls="thanks-versions">
            {$LANG->getModule('thanks_list_member_other_version')} <i class="fa-solid fa-chevron-down"></i>
        </button>
        <div class="collapse" id="thanks-versions">
            <h5>{$LANG->getModule('thanks_other_version')} 4.5.00</h5>
            <p class="mb-0"><a target="_blank" rel="noopener" href="https://github.com/vinades">VINADES.,JSC (281 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (9 commits)</a>, khoaij123 (4 commits), <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung (3 commits)</a>, dat.huynh (3 commits), <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/hiidemo">hiidemo (1 commits)</a>, tuyenh (1 commits), anhtunguyen71 (1 commits)</p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.4.02</h5>
            <p class="mb-0">VINADES.,JSC (3 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (1 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.4.01</h5>
            <p class="mb-0">VINADES.,JSC (41 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (5 commits)</a>, Hoàng Tuyên at VINADES.,JSC (3 commits), <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (2 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.4.00</h5>
            <p class="mb-0">VINADES.,JSC (49 commits), <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (7 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung (5 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (5 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (2 commits)</a>, Hoàng Tuyên at VINADES.,JSC (2 commits)</p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.3.08</h5>
            <p class="mb-0">VINADES.,JSC (28 commits), Hoàng Tuyên at VINADES.,JSC (5 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/tdfoss">TDFOSS.,LTD (1 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.3.07</h5>
            <p class="mb-0">VINADES.,JSC (28 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/ThinhNguyenVB">ThinhNguyenVB (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/tdfoss">TDFOSS.,LTD (1 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.3.06</h5>
            <p class="mb-0">VINADES.,JSC (33 commits), <a target="_blank" rel="noopener" href="https://github.com/tdfoss">TDFOSS.,LTD (5 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (2 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.3.05</h5>
            <p class="mb-0">VINADES.,JSC (38 commits), <a target="_blank" rel="noopener" href="https://github.com/vuthao/">vuthao (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/mynukeviet/">mynukeviet (1 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.3.03</h5>
            <p class="mb-0">VINADES.,JSC (24 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (2 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.3.02</h5>
            <p class="mb-0">VINADES.,JSC (65 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (2 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.3.01</h5>
            <p class="mb-0">VINADES.,JSC (32 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (3 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (1 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.3</h5>
            <p class="mb-0">VINADES.,JSC (132 commits), <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (17 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhyeuviolet">anhyeuviolet (11 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/tdfoss">tdfoss (9 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (8 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/mynukeviet">mynukeviet (4 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung (3 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/trinhthinhhp">trinhthinhhp (1 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.2</h5>
            <p class="mb-0">VINADES.,JSC (238 commits), <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (64 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (31 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (7 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhyeuviolet">anhyeuviolet (5 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/mynukeviet">mynukeviet (4 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung (1 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.1</h5>
            <p class="mb-0">VINADES.,JSC (197 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (131 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhyeuviolet">anhyeuviolet (19 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (17 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/mynukeviet">mynukeviet (10 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thuvp1995">thuvp1995 (9 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thangbv">thangbv (6 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/ngocphan12031995">ngocphan12031995 (5 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/htuyen9x">htuyen9x (4 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/hiidemo">hiidemo (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/trinhthinhhp">trinhthinhhp (1 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/duyetdev">duyetdev (1 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/phongaz">phongaz (1 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/webvang">webvang (1 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 4.0</h5>
            <p class="mb-0">VINADES.,JSC (713 commits) <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (1360 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (547 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/mynukeviet">mynukeviet (219 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/trinhthinhhp">trinhthinhhp (37 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhyeuviolet">anhyeuviolet (25 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/dangdlinhtu">dangdlinhtu (23 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/htuyen9x">htuyen9x (21 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thangbv">thangbv (15 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/PhamQuocTien132">PhamQuocTien132 (9 commits)</a>, mabubeo1990 at gmail.com (8 commits), <a target="_blank" rel="noopener" href="https://github.com/phongaz">phongaz (6 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/tkhuyenbk">tkhuyenbk (2 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/tuanta">tuanta (1 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thethao">thethao (1 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/truongdacngoc1993">truongdacngoc1993 (1 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/webvang">webvang (1 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 3.4</h5>
            <p class="mb-0">VINADES.,JSC (74 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (245 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (60 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung (23 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (5 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 3.3</h5>
            <p class="mb-0">VINADES.,JSC (29 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (24 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (20 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung (5 commits)</a></p>
            <h5>{$LANG->getModule('thanks_other_version')} 3.2</h5>
            <p class="mb-0">VINADES.,JSC (56 commits), <a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (98 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (49 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung (17 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (13 commits)</a>, trankhuyen81 at gmail.com (10 commits)</p>
            <h5>{$LANG->getModule('thanks_other_version')} 3.1</h5>
            <p class="mb-0"><a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (316 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (134 commits)</a>, dinhpc86 at gmail.com (45 commits), <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung (27 commits)</a>, nguyenhung2904 at gmail.com (23 commits), <a target="_blank" rel="noopener" href="https://github.com/hoaquynhtim99">hoaquynhtim99 (9 commits)</a>, tamahari at gmail.com (5 commits), ledinhhung87 at gmail.com (1 commits), mtmost.com at gmail.com (1 commits)</p>
            <h5>{$LANG->getModule('thanks_other_version')} 3.0</h5>
            <p class="mb-0"><a target="_blank" rel="noopener" href="https://github.com/vuthao">vuthao (283 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/anhtunguyen">anhtunguyen (115 commits)</a>, <a target="_blank" rel="noopener" href="https://github.com/thehung">thehung (12 commits)</a>, nguyenhung2904 at gmail.com (3 commits), hungtmit at gmail.com (2 commits)</p>
        </div>
    </div>
</div>
<div class="install-nav">
    <span class="next_step" id="next_step"{if $CHECK_REWRITE} hidden data-toggle="checkRewrite" data-url="{$smarty.const.NV_BASE_SITEURL}install/check.rewrite"{/if}><a class="btn btn-primary" href="{$STEP_URL}2">{$LANG->getModule('next_step')} <i class="fa-solid fa-arrow-right"></i></a></span>
</div>
