function nv_show_list_mods(){document.getElementById("list_mods")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list&num="+nv_randomPassword(8),"list_mods")}function nv_chang_in_menu(a){nv_settimeout_disable("change_inmenu_"+a,5E3);nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_inmenu&mod="+a+"&num="+nv_randomPassword(8),"","nv_chang_in_menu_res")}
function nv_chang_in_menu_res(a){a=a.split("_");var b=document.getElementById("change_inmenu_"+a[1]);if(a[0]!="OK")alert(nv_is_change_act_confirm[2]),b.checked=b.checked==!0?!1:!0,clearTimeout(nv_timer),b.disabled=!0}function nv_chang_submenu(a){nv_settimeout_disable("change_submenu_"+a,5E3);nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_submenu&mod="+a+"&num="+nv_randomPassword(8),"","nv_chang_submenu_res")}
function nv_chang_submenu_res(a){a=a.split("_");var b=document.getElementById("change_submenu_"+a[1]);if(a[0]!="OK")alert(nv_is_change_act_confirm[2]),b.checked=b.checked==!0?!1:!0,clearTimeout(nv_timer),b.disabled=!0}
function nv_chang_weight(a){nv_settimeout_disable("change_weight_"+a,5E3);var b=document.getElementById("change_weight_"+a).options[document.getElementById("change_weight_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_weight&mod="+a+"&new_weight="+b+"&num="+nv_randomPassword(8),"","nv_chang_weight_res")}
function nv_chang_weight_res(a){a.split("_")[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_mods()}function nv_chang_act(a){confirm(nv_is_change_act_confirm[0])?(nv_settimeout_disable("change_act_"+a,5E3),nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_act&mod="+a+"&num="+nv_randomPassword(8),"","nv_chang_act_res")):(a=document.getElementById("change_act_"+a),a.checked=a.checked==!0?!1:!0)}
function nv_chang_act_res(a){a.split("_")[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_mods()}function nv_recreate_mod(a){confirm(nv_is_recreate_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=recreate_mod&mod="+a+"&num="+nv_randomPassword(8),"","nv_recreate_mod_res")}function nv_recreate_mod_res(a){a.split("_")[0]!="OK"?alert(nv_is_recreate_confirm[2]):(alert(nv_is_recreate_confirm[1]),nv_show_list_mods())}
function nv_mod_del(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del&mod="+a,"","nv_mod_del_result");return!1}function nv_mod_del_result(a){a.split("_")[0]=="OK"?window.location.href=script_name+"?"+nv_name_variable+"=modules&"+nv_randomPassword(6)+"="+nv_randomPassword(8):alert(nv_is_del_confirm[2]);return!1}
function nv_show_funcs(a){document.getElementById(a)&&nv_ajax("get",strHref,"aj=show_funcs&num="+nv_randomPassword(8),a)}
function nv_chang_func_weight(a){nv_settimeout_disable("change_weight_"+a,5E3);var b=document.getElementById("change_weight_"+a).options[document.getElementById("change_weight_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_func_weight&fid="+a+"&new_weight="+b+"&num="+nv_randomPassword(8),"","nv_chang_func_weight_res")}
function nv_chang_func_weight_res(a){a=a.split("|");a[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_funcs(a[1])}function nv_chang_func_in_submenu(a){nv_settimeout_disable("chang_func_in_submenu_"+a,5E3);nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_func_submenu&id="+a+"&num="+nv_randomPassword(8),"","nv_chang_func_in_submenu_res")}
function nv_chang_func_in_submenu_res(a){a=a.split("_");var b=document.getElementById("chang_func_in_submenu_"+a[1]);if(a[0]!="OK")alert(nv_is_change_act_confirm[2]),b.checked=b.checked==!0?!1:!0,clearTimeout(nv_timer),b.disabled=!0}function nv_change_custom_name(a,b){nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_custom_name&id="+a+"&num="+nv_randomPassword(8),b)}
function nv_change_custom_name_submit(a,b){var c=rawurlencode(document.getElementById(b).value);nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_custom_name&id="+a+"&save=1&func_custom_name="+c+"&num="+nv_randomPassword(8),"","nv_change_custom_name_res")}function nv_change_custom_name_res(a){a=a.split("|");document.getElementById("chang_func_in_submenu_"+a[1]);a[0]!="OK"?alert(nv_is_change_act_confirm[2]):(nv_show_funcs(a[1]),nv_action_cancel(a[2]))}
function nv_action_cancel(a){document.getElementById(a).innerHTML=""}function nv_chang_bl_weight(a){nv_settimeout_disable("change_bl_weight_"+a,5E3);var b=document.getElementById("change_bl_weight_"+a).options[document.getElementById("change_bl_weight_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_block_weight&id="+a+"&new_weight="+b+"&num="+nv_randomPassword(8),"","nv_chang_bl_weight_res")}
function nv_chang_bl_weight_res(a){a=a.split("|");a[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_bl_list(a[1],a[2],a[3])}function nv_show_bl(a,b){nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=show_block&id="+a+"&num="+nv_randomPassword(8),b)}function nv_del_bl(a){confirm(nv_is_del_confirm[0])&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_block&id="+a,"","nv_del_bl_res");return!1}
function nv_del_bl_res(a){a=a.split("|");a[0]=="OK"?nv_bl_list(a[1],a[2],a[3]):alert(nv_is_del_confirm[2]);return!1};