<?php

// autoload.php @generated by Composer

if( ! defined( 'NV_IS_MOD_USER' ) ) die( 'Stop!!!' );

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit49e49518769c3ffc5ffc83d0690e6e67::getLoader();