jQuery.fn.extend({selectbox:function(m){return this.each(function(){new jQuery.SelectBox(this,m)})}});if(!window.console)var console={log:function(){}};
jQuery.SelectBox=function(m,t){function l(){k=0;d.hide()}function q(c){var b=jQuery("li",d);if(!b||b.length==0)return false;for(firstchoice=0;$(b[firstchoice]).hasClass(a.groupClass);)firstchoice++;e+=c;if($(b[e]).hasClass(a.groupClass))e+=c;if(e<firstchoice)a.loopnoStep?e=b.size()-1:e=b.size();else if(a.loopnoStep&&e>b.size()-1)e=firstchoice;else if(e>b.size())e=firstchoice;c=b;var g=jQuery(c[e]).get(0);c=d.get(0);if(g.offsetTop+g.offsetHeight>c.scrollTop+c.clientHeight)c.scrollTop=g.offsetTop+g.offsetHeight-
c.clientHeight;else if(g.offsetTop<c.scrollTop)c.scrollTop=g.offsetTop;b.removeClass(a.hoverClass);jQuery(b[e]).addClass(a.hoverClass)}function r(){var c=jQuery("li."+a.currentClass,d).get(0),b=(""+c.id).split("_");b=b[b.length-1];if(a.onChangeCallback){f.get(0).selectedIndex=$("li",d).index(c);a.onChangeParams={selectedVal:f.val()};a.onChangeCallback(a.onChangeParams)}else{f.val(b);f.change()}a.inputType=="span"?h.html($(c).html()):h.val($(c).html());return true}function u(c){var b=[],g=document.createElement("ul");
b=f.children("option");if(b.length==0){var n=[];n=f.children("optgroup");for(x=0;x<n.length;x++){b=$("#"+n[x].id).children("option");var o=document.createElement("li");o.setAttribute("id",c+"_"+$(this).val());o.innerHTML=$("#"+n[x].id).attr("label");o.className=a.groupClass;g.appendChild(o);b.each(function(){var i=document.createElement("li");i.setAttribute("id",c+"_"+$(this).val());i.innerHTML=$(this).html();if($(this).is(":selected")){h.html($(this).html());$(i).addClass(a.currentClass)}g.appendChild(i);
$(i).mouseover(function(j){k=1;a.debug&&console.log("over on : "+this.id);jQuery(j.target,d).addClass(a.hoverClass)}).mouseout(function(j){k=-1;a.debug&&console.log("out on : "+this.id);jQuery(j.target,d).removeClass(a.hoverClass)}).click(function(){$("li."+a.hoverClass,d).get(0);a.debug&&console.log("click on :"+this.id);$("li."+a.currentClass,d).removeClass(a.currentClass);$(this).addClass(a.currentClass);r();f.get(0).blur();l()})})}}else b.each(function(){var i=document.createElement("li");i.setAttribute("id",
c+"_"+$(this).val());i.innerHTML=$(this).html();if($(this).is(":selected")){h.val($(this).html());$(i).addClass(a.currentClass)}g.appendChild(i);$(i).mouseover(function(j){k=1;a.debug&&console.log("over on : "+this.id);jQuery(j.target,d).addClass(a.hoverClass)}).mouseout(function(j){k=-1;a.debug&&console.log("out on : "+this.id);jQuery(j.target,d).removeClass(a.hoverClass)}).click(function(){$("li."+a.hoverClass,d).get(0);a.debug&&console.log("click on :"+this.id);$("li."+a.currentClass,d).removeClass(a.currentClass);
$(this).addClass(a.currentClass);r();f.get(0).blur();l()})});return g}var a=t||{};a.inputType=a.inputType||"input";a.inputClass=a.inputClass||"selectbox";a.containerClass=a.containerClass||"selectbox-wrapper";a.hoverClass=a.hoverClass||"current";a.currentClass=a.currentClass||"selected";a.groupClass=a.groupClass||"groupname";a.maxHeight=a.maxHeight||200;a.loopnoStep=a.loopnoStep||false;a.onChangeCallback=a.onChangeCallback||false;a.onChangeParams=a.onChangeParams||false;a.debug=a.debug||false;var p=
m.id,e=0,s=false,k=0,f=jQuery(m),d=function(c){var b=document.createElement("div");d=jQuery(b);d.attr("id",p+"_container");d.addClass(c.containerClass);d.css("display","none");return d}(a),h=function(c){if(a.inputType=="span"){var b=document.createElement("span");b=jQuery(b);b.attr("id",p+"_input");b.addClass(c.inputClass);b.attr("tabIndex",f.attr("tabindex"))}else{b=document.createElement("input");b=jQuery(b);b.attr("id",p+"_input");b.attr("type","text");b.addClass(c.inputClass);b.attr("autocomplete",
"off");b.attr("readonly","readonly");b.attr("tabIndex",f.attr("tabindex"));b.css("width",f.css("width"))}return b}(a);f.hide().before(h).before(d);(function(){d.append(u(h.attr("id"))).hide();var c=h.css("width");if(d.height()>a.maxHeight){d.width(parseInt(c)+parseInt(h.css("paddingRight"))+parseInt(h.css("paddingLeft")));d.height(a.maxHeight)}else d.width(c)})();h.click(function(){s||d.toggle()}).focus(function(){if(d.not(":visible")){s=true;d.show()}}).keydown(function(c){switch(c.keyCode){case 38:c.preventDefault();
q(-1);break;case 40:c.preventDefault();q(1);break;case 13:c.preventDefault();$("li."+a.hoverClass).trigger("click");break;case 27:l()}}).blur(function(){if(d.is(":visible")&&k>0)a.debug&&console.log("container visible and has focus");else if(jQuery.browser.msie&&jQuery.browser.version.substr(0,1)<8||jQuery.browser.safari)document.activeElement.getAttribute("id").indexOf("_container")==-1?l():h.focus();else l()})};