function nv_chang_cat(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_cat&catid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_cat_result")}
function nv_chang_cat_result(a){a=a.split("_");a[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);a=parseInt(a[1]);nv_show_list_cat(a)}function nv_show_list_cat(a){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_cat&parentid="+a+"&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_cat(a){nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_cat&catid="+a,"","nv_del_cat_result");return false}
function nv_del_cat_result(a){var b=a.split("_");if(b[0]=="OK"){a=parseInt(b[1]);nv_show_list_cat(a)}else if(b[0]=="CONFIRM"){if(confirm(nv_is_del_confirm[0])){a=b[1];b=b[2];nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_cat&catid="+a+"&delallcheckss="+b,"","nv_del_cat_result")}}else if(b[0]=="ERR"&&b[1]=="CAT")alert(b[2]);else if(b[0]=="ERR"&&b[1]=="ROWS"){if(confirm(b[4])){a=b[2];b=b[3];nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+
"=del_cat&catid="+a+"&delallcheckss="+b,"edit","");parent.location='#edit';}}else alert(nv_is_del_confirm[2]);return false}function nv_chang_topic(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_topic&topicid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_topic_result")}
function nv_chang_topic_result(a){a.split("_")[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_topic()}function nv_show_list_topic(){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_topic&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_topic(a){nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_topic&topicid="+a,"","nv_del_topic_result")}
function nv_del_topic_result(a){a=a.split("_");if(a[0]=="OK")nv_show_list_topic();else if(a[0]=="ERR")if(a[1]=="ROWS")confirm(a[4])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_topic&topicid="+a[2]+"&checkss="+a[3],"","nv_del_topic_result");else alert(a[1]);else alert(nv_is_del_confirm[2]);return false}
function nv_chang_sources(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_source&sourceid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_sources_result")}
function nv_chang_sources_result(a){a.split("_")[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_source()}function nv_show_list_source(){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_source&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_source(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_source&sourceid="+a,"","nv_del_source_result");return false}function nv_del_source_result(a){a=a.split("_");if(a[0]=="OK")nv_show_list_source();else a[0]=="ERR"?alert(a[1]):alert(nv_is_del_confirm[2]);return false}
function nv_del_block_cat(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_block_cat&bid="+a,"","nv_del_block_cat_result");return false}function nv_del_block_cat_result(a){a=a.split("_");if(a[0]=="OK")nv_show_list_block_cat();else a[0]=="ERR"?alert(a[1]):alert(nv_is_del_confirm[2]);return false}
function nv_chang_block_cat(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=chang_block_cat&bid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_block_cat_result")}
function nv_chang_block_cat_result(a){a.split("_")[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_block_cat()}function nv_show_list_block_cat(){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_block_cat&num="+nv_randomPassword(8),"module_show_list")}
function nv_chang_block(a,b,c){nv_settimeout_disable("id_weight_"+b,5E3);var d=document.getElementById("id_weight_"+b).options[document.getElementById("id_weight_"+b).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_block&id="+b+"&bid="+a+"&&mod="+c+"&new_vid="+d+"&num="+nv_randomPassword(8),"","nv_chang_block_result")}
function nv_chang_block_result(a){a=a.split("_");a[0]!="OK"&&alert(nv_is_change_act_confirm[2]);a=parseInt(a[1]);nv_show_list_block(a)}function nv_show_list_block(a){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_block&bid="+a+"&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_block_list(a,b){var c="",d=a["idcheck[]"];if(d.length)for(var e=0;e<d.length;e++){if(d[e].checked)c=c+","+d[e].value}else if(d.checked)c=c+","+d.value;c!=""&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_block&del_list="+c+"&bid="+b+"&num="+nv_randomPassword(8),"","nv_chang_block_result")}
function nv_main_action(a,b,c){var d=a["idcheck[]"];a="";if(d.length)for(var e=0;e<d.length;e++){if(d[e].checked)a=a+d[e].value+","}else if(d.checked)a=a+d.value+",";if(a!=""){c=document.getElementById("action").value;if(c=="delete")confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_content&listid="+a+"&checkss="+b,"","nv_del_content_result");else window.location.href=c=="addtoblock"?script_name+"?"+nv_name_variable+"="+nv_module_name+
"&"+nv_fc_variable+"=block&listid="+a+"#add":c=="publtime"?script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=publtime&listid="+a+"&checkss="+b:c=="exptime"?script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=exptime&listid="+a+"&checkss="+b:script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=addtotopics&listid="+a}else alert(c)}
function nv_del_content(a,b){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_content&id="+a+"&checkss="+b,"","nv_del_content_result");return false}function nv_check_movecat(a,b){if(a.catidnews.value==0){alert(b);return false}}
function nv_del_content_result(a){a=a.split("_");if(a[0]=="OK")window.location.href=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=main";else a[0]=="ERR"?alert(a[1]):alert(nv_is_del_confirm[2]);return false}
function create_keywords(){var a=strip_tags(document.getElementById("keywords").value);a!=""&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=keywords&content="+encodeURIComponent(a),"","res_keywords");return false}function res_keywords(a){if(a!="n/a")document.getElementById("keywords").value=a;else document.getElementById("keywords").value="";return false}
function get_alias(){var a=strip_tags(document.getElementById("idtitle").value);a!=""&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=alias&title="+encodeURIComponent(a),"","res_get_alias");return false}function res_get_alias(a){if(a!="")document.getElementById("idalias").value=a;else document.getElementById("idalias").value="";return false}
function findValue(a){if(a==null)return alert("No match!");return a.extra?a.extra[0]:a.selectValue}function selectItem(a){sValue=findValue(a)}function formatItem(a){return a[0]+" ("+a[1]+")"}
$(document).ready(function(){$(".message_list .message_body:gt(1)").hide();$(".message_list li:gt(5)").hide();$(".message_head").click(function(){$(this).next(".message_body").slideToggle(500);return false});$(".collpase_all_message").click(function(){$(".message_body").slideUp(500);return false});$(".show_all_message").click(function(){$(".message_body").slideDown(1E3);return false})});