<?php

/**
 * @Project NUKEVIET 3.x
 * @Author VINADES.,JSC (contact@vinades.vn)
 * @Copyright (C) 2012 VINADES.,JSC. All rights reserved
 * @Createdate 31/05/2010, 00:36
 */

function nv_create_table_news( $catid )
{
	global $db, $db_config, $lang_data;

	$db->sql_query( "SET SQL_QUOTE_SHOW_CREATE = 1" );
	$result = $db->sql_query( "SHOW CREATE TABLE `" . $db_config['prefix'] . "_fr_news_rows`" );
	$show = $db->sql_fetchrow( $result );
	$db->sql_freeresult( $result );

	$show = preg_replace( '/(KEY[^\(]+)(\([^\)]+\))[\s\r\n\t]+(USING BTREE)/i', '\\1\\3 \\2', $show[1] );
	$sql = preg_replace( '/(default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP|DEFAULT CHARSET=\w+|COLLATE=\w+|character set \w+|collate \w+|AUTO_INCREMENT=\w+)/i', ' \\1', $show );
	$sql = str_replace( $db_config['prefix'] . "_" . $lang_data . "_news_rows", $db_config['prefix'] . "_" . $lang_data . "_news_" . $catid, $sql );

	$db->sql_query( $sql );
}

$sql_create_table = array();

$sql_create_table[] = "TRUNCATE TABLE `" . $db_config['prefix'] . "_" . $lang_data . "_modules`";
$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_modules` (`title`, `module_file`, `module_data`, `custom_title`, `admin_title`, `set_time`, `main_file`, `admin_file`, `theme`, `mobile`, `description`, `keywords`, `groups_view`, `in_menu`, `weight`, `submenu`, `act`, `admins`, `rss`) VALUES
('about', 'about', 'about', 'À propos', '', 1276333182, 1, 1, '', 'mobile_nukeviet', '', '', '0', 1, 1, 1, 1, '', 0),
('news', 'news', 'news', 'News', '', 1270400000, 1, 1, '', 'mobile_nukeviet', '', '', '0', 1, 2, 1, 1, '', 1),
('users', 'users', 'users', 'Compte d&#039;utilisateur', '', 1274080277, 1, 1, '', 'mobile_nukeviet', '', '', '0', 1, 3, 1, 1, '', 0),
('contact', 'contact', 'contact', 'Contact', '', 1275351337, 1, 1, '', 'mobile_nukeviet', '', '', '0', 1, 4, 1, 1, '', 0),
('statistics', 'statistics', 'statistics', 'Statistiques', '', 1276520928, 1, 0, '', 'mobile_nukeviet', '', 'online, statistics', '0', 1, 5, 1, 1, '', 0),
('voting', 'voting', 'voting', 'Sondage', '', 1275315261, 1, 1, '', 'mobile_nukeviet', '', '', '0', 0, 6, 1, 1, '', 1),
('banners', 'banners', 'banners', 'Publicité', '', 1270400000, 1, 1, '', 'mobile_nukeviet', '', '', '0', 0, 7, 1, 1, '', 0),
('search', 'search', 'search', 'Recherche', '', 1273474173, 1, 0, '', 'mobile_nukeviet', '', '', '0', 0, 8, 1, 1, '', 0),
('menu', 'menu', 'menu', 'Menu Site', '', 1295287334, 0, 1, '', 'mobile_nukeviet', '', '', '0', 0, 9, 1, 1, '', 0),
('rss', 'rss', 'rss', 'Rss', '', 1279366705, 1, 1, '', 'mobile_nukeviet', '', '', '0', 0, 10, 1, 1, '', 0)";

$sql_create_table[] = "TRUNCATE TABLE `" . $db_config['prefix'] . "_" . $lang_data . "_modfuncs`";
$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_modfuncs` (`func_id`, `func_name`, `func_custom_name`, `in_module`, `show_func`, `in_submenu`, `subweight`, `setting`) VALUES
(1, 'Sitemap', 'Sitemap', 'about', 0, 0, 0, ''),
(2, 'main', 'Main', 'about', 1, 0, 1, ''),
(3, 'Sitemap', 'Sitemap', 'news', 0, 0, 0, ''),
(4, 'comment', 'Comment', 'news', 0, 0, 0, ''),
(5, 'content', 'Content', 'news', 1, 0, 1, ''),
(6, 'detail', 'Detail', 'news', 1, 0, 2, ''),
(7, 'main', 'Main', 'news', 1, 0, 3, ''),
(8, 'postcomment', 'Postcomment', 'news', 0, 0, 0, ''),
(9, 'print', 'Print', 'news', 0, 0, 0, ''),
(10, 'rating', 'Rating', 'news', 0, 0, 0, ''),
(11, 'rss', 'Rss', 'news', 0, 0, 0, ''),
(12, 'savefile', 'Savefile', 'news', 0, 0, 0, ''),
(13, 'search', 'Search', 'news', 1, 0, 4, ''),
(14, 'sendmail', 'Sendmail', 'news', 0, 0, 0, ''),
(15, 'topic', 'Topic', 'news', 1, 0, 5, ''),
(16, 'viewcat', 'Viewcat', 'news', 1, 0, 6, ''),
(17, 'active', 'Active', 'users', 1, 0, 8, ''),
(18, 'changepass', 'Changer le mot de passe', 'users', 1, 1, 6, ''),
(19, 'editinfo', 'Editinfo', 'users', 1, 0, 10, ''),
(20, 'login', 'Se connecter', 'users', 1, 1, 2, ''),
(21, 'logout', 'Logout', 'users', 1, 1, 3, ''),
(22, 'lostactivelink', 'Lostactivelink', 'users', 1, 0, 9, ''),
(23, 'lostpass', 'Mot de passe oublié?', 'users', 1, 1, 5, ''),
(24, 'main', 'Main', 'users', 1, 1, 1, ''),
(25, 'openid', 'Openid', 'users', 1, 1, 7, ''),
(26, 'register', 'S&#039;inscrire', 'users', 1, 1, 4, ''),
(27, 'main', 'Main', 'contact', 1, 0, 1, ''),
(28, 'allbots', 'Par Moteur de recherche', 'statistics', 1, 1, 6, ''),
(29, 'allbrowsers', 'Par Navigateur', 'statistics', 1, 1, 4, ''),
(30, 'allcountries', 'Par Pays', 'statistics', 1, 1, 3, ''),
(31, 'allos', 'Par Système d&#039;exploitation', 'statistics', 1, 1, 5, ''),
(32, 'allreferers', 'Par Site', 'statistics', 1, 1, 2, ''),
(33, 'main', 'Main', 'statistics', 1, 0, 1, ''),
(34, 'referer', 'referer', 'statistics', 1, 0, 7, ''),
(35, 'main', 'Main', 'voting', 1, 0, 0, ''),
(36, 'addads', 'Addads', 'banners', 1, 0, 1, ''),
(37, 'cledit', 'Cledit', 'banners', 0, 0, 0, ''),
(38, 'click', 'Click', 'banners', 0, 0, 0, ''),
(39, 'clientinfo', 'Clientinfo', 'banners', 1, 0, 2, ''),
(40, 'clinfo', 'Clinfo', 'banners', 0, 0, 0, ''),
(41, 'logininfo', 'Logininfo', 'banners', 0, 0, 0, ''),
(42, 'main', 'Main', 'banners', 1, 0, 3, ''),
(43, 'stats', 'Stats', 'banners', 1, 0, 4, ''),
(44, 'viewmap', 'Viewmap', 'banners', 0, 0, 0, ''),
(45, 'adv', 'Adv', 'search', 0, 0, 0, ''),
(46, 'main', 'Main', 'search', 1, 0, 1, ''),
(47, 'main', 'Main', 'rss', 1, 0, 1, ''),
(48, 'regroups', 'Regroups', 'users', 1, 0, 1, ''),
(50, 'memberlist', 'Liste des membres', 'users', 1, 1, 1, ''),
(51, 'groups', 'Groups', 'news', 1, 0, 7, '')";

$sql_create_table[] = "REPLACE INTO `" . $db_config['prefix'] . "_" . $lang_data . "_modthemes` (`func_id`, `layout`, `theme`) VALUES
(0, 'body-right', 'modern'),
(0, 'left-body-right', 'default'),
(2, 'body', 'modern'),
(2, 'left-body-right', 'default'),
(5, 'body-right', 'modern'),
(5, 'left-body-right', 'default'),
(6, 'body-right', 'modern'),
(6, 'left-body-right', 'default'),
(7, 'body-right', 'modern'),
(7, 'left-body-right', 'default'),
(13, 'body-right', 'modern'),
(13, 'left-body-right', 'default'),
(15, 'body-right', 'modern'),
(15, 'left-body-right', 'default'),
(16, 'body-right', 'modern'),
(16, 'left-body-right', 'default'),
(17, 'body-right', 'modern'),
(17, 'left-body-right', 'default'),
(18, 'body-right', 'modern'),
(18, 'left-body-right', 'default'),
(19, 'body-right', 'modern'),
(19, 'left-body-right', 'default'),
(20, 'body-right', 'modern'),
(20, 'left-body-right', 'default'),
(21, 'body-right', 'modern'),
(21, 'left-body-right', 'default'),
(22, 'body-right', 'modern'),
(22, 'left-body-right', 'default'),
(23, 'body-right', 'modern'),
(23, 'left-body-right', 'default'),
(24, 'body-right', 'modern'),
(24, 'left-body-right', 'default'),
(25, 'body-right', 'modern'),
(25, 'left-body-right', 'default'),
(26, 'body-right', 'modern'),
(26, 'left-body-right', 'default'),
(27, 'body-right', 'modern'),
(27, 'left-body-right', 'default'),
(28, 'body', 'modern'),
(28, 'left-body', 'default'),
(29, 'body', 'modern'),
(29, 'left-body', 'default'),
(30, 'body', 'modern'),
(30, 'left-body', 'default'),
(31, 'body', 'modern'),
(31, 'left-body', 'default'),
(32, 'body', 'modern'),
(32, 'left-body', 'default'),
(33, 'body', 'modern'),
(33, 'left-body', 'default'),
(34, 'body', 'modern'),
(34, 'left-body', 'default'),
(36, 'body-right', 'modern'),
(36, 'left-body-right', 'default'),
(39, 'body-right', 'modern'),
(39, 'left-body-right', 'default'),
(42, 'body-right', 'modern'),
(42, 'left-body-right', 'default'),
(43, 'body-right', 'modern'),
(43, 'left-body-right', 'default'),
(46, 'body-right', 'modern'),
(46, 'left-body-right', 'default'),
(47, 'body', 'modern'),
(47, 'left-body-right', 'default'),
(48, 'body-right', 'modern'),
(48, 'left-body-right', 'default')";

$sql_create_table[] = "REPLACE INTO `" . $db_config['prefix'] . "_" . $lang_data . "_modthemes` (`func_id`, `layout`, `theme`) VALUES
(0, 'body', 'mobile_nukeviet'),
(2, 'body', 'mobile_nukeviet'),
(5, 'body', 'mobile_nukeviet'),
(6, 'body', 'mobile_nukeviet'),
(7, 'body', 'mobile_nukeviet'),
(13, 'body', 'mobile_nukeviet'),
(15, 'body', 'mobile_nukeviet'),
(16, 'body', 'mobile_nukeviet'),
(17, 'body', 'mobile_nukeviet'),
(18, 'body', 'mobile_nukeviet'),
(19, 'body', 'mobile_nukeviet'),
(20, 'body', 'mobile_nukeviet'),
(21, 'body', 'mobile_nukeviet'),
(22, 'body', 'mobile_nukeviet'),
(23, 'body', 'mobile_nukeviet'),
(24, 'body', 'mobile_nukeviet'),
(25, 'body', 'mobile_nukeviet'),
(26, 'body', 'mobile_nukeviet'),
(27, 'body', 'mobile_nukeviet'),
(28, 'body', 'mobile_nukeviet'),
(29, 'body', 'mobile_nukeviet'),
(30, 'body', 'mobile_nukeviet'),
(31, 'body', 'mobile_nukeviet'),
(32, 'body', 'mobile_nukeviet'),
(33, 'body', 'mobile_nukeviet'),
(34, 'body', 'mobile_nukeviet'),
(36, 'body', 'mobile_nukeviet'),
(39, 'body', 'mobile_nukeviet'),
(42, 'body', 'mobile_nukeviet'),
(43, 'body', 'mobile_nukeviet'),
(46, 'body', 'mobile_nukeviet'),
(47, 'body', 'mobile_nukeviet'),
(48, 'body', 'mobile_nukeviet')";

$sql_create_table[] = "REPLACE INTO `" . $db_config['prefix'] . "_" . $lang_data . "_modthemes` (`func_id`, `layout`, `theme`) VALUES
(35, 'body-right', 'modern'),
(35, 'left-body-right', 'default'),
(35, 'body', 'mobile_nukeviet')";

$sql_create_table[] = "REPLACE INTO `" . $db_config['prefix'] . "_" . $lang_data . "_modthemes` (`func_id`, `layout`, `theme`) VALUES
(50, 'body-right', 'modern'),
(50, 'left-body-right', 'default'),
(50, 'body', 'mobile_nukeviet')";

$sql_create_table[] = "TRUNCATE TABLE `" . $db_config['prefix'] . "_" . $lang_data . "_blocks_groups`";
$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_blocks_groups` (`bid`, `theme`, `module`, `file_name`, `title`, `link`, `template`, `position`, `exp_time`, `active`, `groups_view`, `all_func`, `weight`, `config`) VALUES
(1, 'default', 'news', 'global.block_category.php', 'Menu', '', '', '[LEFT]', 0, 1, '0', 0, 1, 'a:1:{s:12:\"title_length\";i:25;}'),
(2, 'default', 'statistics', 'global.counter.php', 'Statistiques', '', '', '[LEFT]', 0, 1, '0', 1, 2, ''),
(3, 'default', 'banners', 'global.banners.php', 'Publicité à côté', '', '', '[LEFT]', 0, 1, '0', 1, 3, 'a:1:{s:12:\"idplanbanner\";i:2;}'),
(4, 'default', 'about', 'global.about.php', 'À Propos', '', 'orange', '[RIGHT]', 0, 1, '0', 1, 1, ''),
(5, 'default', 'users', 'global.voting_random.php', 'Identification', '', '', '[RIGHT]', 0, 1, '0', 1, 2, ''),
(6, 'default', 'voting', 'global.voting.php', 'Sondage', '', '', '[RIGHT]', 0, 1, '0', 1, 3, ''),
(7, 'default', 'news', 'module.block_headline.php', 'Hot news', '', 'no_title', '[TOP]', 0, 1, '0', 0, 1, ''),
(8, 'default', 'banners', 'global.banners.php', 'Publicité du centre', '', 'no_title', '[TOP]', 0, 1, '0', 1, 2, 'a:1:{s:12:\"idplanbanner\";i:1;}'),
(9, 'modern', 'news', 'module.block_newscenter.php', 'Nouvelles', '', 'no_title', '[HEADER]', 0, 1, '0', 0, 1, ''),
(10, 'modern', 'about', 'global.about.php', 'À Propos', '', 'no_title_html', '[RIGHT]', 0, 1, '0', 1, 1, ''),
(11, 'modern', 'users', 'global.login.php', 'Identification', '', '', '[RIGHT]', 0, 1, '0', 1, 2, ''),
(12, 'modern', 'voting', 'global.voting_random.php', 'Sondage', '', '', '[RIGHT]', 0, 1, '0', 1, 3, ''),
(13, 'modern', 'statistics', 'global.counter.php', 'Statistiques', '', '', '[RIGHT]', 0, 1, '0', 1, 4, ''),
(14, 'modern', 'news', 'module.block_newsright.php', 'News Right', '', 'no_title', '[RIGHT]', 0, 1, '0', 0, 5, ''),
(15, 'modern', 'banners', 'global.banners.php', 'Bannière Top', '', 'no_title', '[TOPADV]', 0, 1, '0', 1, 1, 'a:1:{s:12:\"idplanbanner\";i:1;}'),
(16, 'modern', 'menu', 'global.menu_theme_modern.php', 'global menu theme modern', '', 'no_title', '[MENU_SITE]', 0, 1, '0', 1, 1, ''),
(17, 'default', 'menu', 'global.menu_theme_default.php', 'global menu theme default', '', 'no_title', '[MENU_SITE]', 0, 1, '0', 1, 1, ''),
(18, 'modern', 'global', 'global.html.php', 'footer site', '', 'no_title', '[FOOTER_SITE]', 0, 1, '0', 1, 1, 'a:1:{s:11:\"htmlcontent\";s:207:\"© Copyright NukeViet 3. All right reserved.<br  />Powered by <a href=\"http://nukeviet.vn/\" title=\"NukeViet CMS\">NukeViet CMS</a>. Design by <a href=\"http://vinades.vn/\" title=\"VINADES.,JSC\">VINADES.,JSC</a>\";}'),
(19, 'default', 'global', 'global.html.php', 'footer site', '', 'no_title', '[FOOTER_SITE]', 0, 1, '0', 1, 1, 'a:1:{s:11:\"htmlcontent\";s:231:\"<p class=\"footer\"> © Copyright NukeViet 3. All right reserved.</p><p> Powered by <a href=\"http://nukeviet.vn/\" title=\"NukeViet CMS\">NukeViet CMS</a>. Design by <a href=\"http://vinades.vn/\" title=\"VINADES.,JSC\">VINADES.,JSC</a></p>\";}'), 
(20, 'mobile_nukeviet', 'menu', 'global.menu_theme_default.php', 'global menu theme default', '', 'no_title', '[MENU_SITE]', 0, 1, '0', 1, 1, '')";

$sql_create_table[] = "TRUNCATE TABLE `" . $db_config['prefix'] . "_" . $lang_data . "_blocks_weight`";
$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_blocks_weight` (`bid`, `func_id`, `weight`) VALUES
(1, 5, 1),
(1, 6, 1),
(1, 7, 1),
(1, 13, 1),
(1, 15, 1),
(1, 16, 1),
(2, 2, 1),
(2, 36, 1),
(2, 39, 1),
(2, 42, 1),
(2, 43, 1),
(2, 27, 1),
(2, 5, 2),
(2, 6, 2),
(2, 7, 2),
(2, 13, 2),
(2, 15, 2),
(2, 16, 2),
(2, 47, 1),
(2, 46, 1),
(2, 28, 1),
(2, 29, 1),
(2, 30, 1),
(2, 31, 1),
(2, 32, 1),
(2, 33, 1),
(2, 34, 1),
(2, 17, 1),
(2, 25, 1),
(2, 24, 1),
(2, 23, 1),
(2, 22, 1),
(2, 21, 1),
(2, 20, 1),
(2, 19, 1),
(2, 18, 1),
(2, 26, 1),
(3, 2, 2),
(3, 36, 2),
(3, 39, 2),
(3, 42, 2),
(3, 43, 2),
(3, 27, 2),
(3, 5, 3),
(3, 6, 3),
(3, 7, 3),
(3, 13, 3),
(3, 15, 3),
(3, 16, 3),
(3, 47, 2),
(3, 46, 2),
(3, 28, 2),
(3, 29, 2),
(3, 30, 2),
(3, 31, 2),
(3, 32, 2),
(3, 33, 2),
(3, 34, 2),
(3, 17, 2),
(3, 25, 2),
(3, 24, 2),
(3, 23, 2),
(3, 22, 2),
(3, 21, 2),
(3, 20, 2),
(3, 19, 2),
(3, 18, 2),
(3, 26, 2),
(4, 2, 1),
(4, 36, 1),
(4, 39, 1),
(4, 42, 1),
(4, 43, 1),
(4, 27, 1),
(4, 5, 1),
(4, 6, 1),
(4, 7, 1),
(4, 13, 1),
(4, 15, 1),
(4, 16, 1),
(4, 47, 1),
(4, 46, 1),
(4, 28, 1),
(4, 29, 1),
(4, 30, 1),
(4, 31, 1),
(4, 32, 1),
(4, 33, 1),
(4, 34, 1),
(4, 17, 1),
(4, 25, 1),
(4, 24, 1),
(4, 23, 1),
(4, 22, 1),
(4, 21, 1),
(4, 20, 1),
(4, 19, 1),
(4, 18, 1),
(4, 26, 1),
(5, 2, 2),
(5, 36, 2),
(5, 39, 2),
(5, 42, 2),
(5, 43, 2),
(5, 27, 2),
(5, 5, 2),
(5, 6, 2),
(5, 7, 2),
(5, 13, 2),
(5, 15, 2),
(5, 16, 2),
(5, 47, 2),
(5, 46, 2),
(5, 28, 2),
(5, 29, 2),
(5, 30, 2),
(5, 31, 2),
(5, 32, 2),
(5, 33, 2),
(5, 34, 2),
(5, 17, 2),
(5, 25, 2),
(5, 24, 2),
(5, 23, 2),
(5, 22, 2),
(5, 21, 2),
(5, 20, 2),
(5, 19, 2),
(5, 18, 2),
(5, 26, 2),
(6, 2, 3),
(6, 36, 3),
(6, 39, 3),
(6, 42, 3),
(6, 43, 3),
(6, 27, 3),
(6, 5, 3),
(6, 6, 3),
(6, 7, 3),
(6, 13, 3),
(6, 15, 3),
(6, 16, 3),
(6, 47, 3),
(6, 46, 3),
(6, 28, 3),
(6, 29, 3),
(6, 30, 3),
(6, 31, 3),
(6, 32, 3),
(6, 33, 3),
(6, 34, 3),
(6, 17, 3),
(6, 25, 3),
(6, 24, 3),
(6, 23, 3),
(6, 22, 3),
(6, 21, 3),
(6, 20, 3),
(6, 19, 3),
(6, 18, 3),
(6, 26, 3),
(7, 7, 1),
(8, 2, 1),
(8, 36, 1),
(8, 39, 1),
(8, 42, 1),
(8, 43, 1),
(8, 27, 1),
(8, 5, 1),
(8, 6, 1),
(8, 7, 2),
(8, 13, 1),
(8, 15, 1),
(8, 16, 1),
(8, 47, 1),
(8, 46, 1),
(8, 28, 1),
(8, 29, 1),
(8, 30, 1),
(8, 31, 1),
(8, 32, 1),
(8, 33, 1),
(8, 34, 1),
(8, 17, 1),
(8, 25, 1),
(8, 24, 1),
(8, 23, 1),
(8, 22, 1),
(8, 21, 1),
(8, 20, 1),
(8, 19, 1),
(8, 18, 1),
(8, 26, 1),
(9, 7, 1),
(10, 2, 1),
(10, 36, 1),
(10, 39, 1),
(10, 42, 1),
(10, 43, 1),
(10, 27, 1),
(10, 5, 1),
(10, 6, 1),
(10, 7, 1),
(10, 13, 1),
(10, 15, 1),
(10, 16, 1),
(10, 47, 1),
(10, 46, 1),
(10, 28, 1),
(10, 29, 1),
(10, 30, 1),
(10, 31, 1),
(10, 32, 1),
(10, 33, 1),
(10, 34, 1),
(10, 17, 1),
(10, 25, 1),
(10, 24, 1),
(10, 23, 1),
(10, 22, 1),
(10, 21, 1),
(10, 20, 1),
(10, 19, 1),
(10, 18, 1),
(10, 26, 1),
(11, 2, 2),
(11, 36, 2),
(11, 39, 2),
(11, 42, 2),
(11, 43, 2),
(11, 27, 2),
(11, 5, 2),
(11, 6, 2),
(11, 7, 2),
(11, 13, 2),
(11, 15, 2),
(11, 16, 2),
(11, 47, 2),
(11, 46, 2),
(11, 28, 2),
(11, 29, 2),
(11, 30, 2),
(11, 31, 2),
(11, 32, 2),
(11, 33, 2),
(11, 34, 2),
(11, 17, 2),
(11, 25, 2),
(11, 24, 2),
(11, 23, 2),
(11, 22, 2),
(11, 21, 2),
(11, 20, 2),
(11, 19, 2),
(11, 18, 2),
(11, 26, 2),
(12, 2, 3),
(12, 36, 3),
(12, 39, 3),
(12, 42, 3),
(12, 43, 3),
(12, 27, 3),
(12, 5, 3),
(12, 6, 3),
(12, 7, 3),
(12, 13, 3),
(12, 15, 3),
(12, 16, 3),
(12, 47, 3),
(12, 46, 3),
(12, 28, 3),
(12, 29, 3),
(12, 30, 3),
(12, 31, 3),
(12, 32, 3),
(12, 33, 3),
(12, 34, 3),
(12, 17, 3),
(12, 25, 3),
(12, 24, 3),
(12, 23, 3),
(12, 22, 3),
(12, 21, 3),
(12, 20, 3),
(12, 19, 3),
(12, 18, 3),
(12, 26, 3),
(13, 2, 4),
(13, 36, 4),
(13, 39, 4),
(13, 42, 4),
(13, 43, 4),
(13, 27, 4),
(13, 5, 4),
(13, 6, 4),
(13, 7, 4),
(13, 13, 4),
(13, 15, 4),
(13, 16, 4),
(13, 47, 4),
(13, 46, 4),
(13, 28, 4),
(13, 29, 4),
(13, 30, 4),
(13, 31, 4),
(13, 32, 4),
(13, 33, 4),
(13, 34, 4),
(13, 17, 4),
(13, 25, 4),
(13, 24, 4),
(13, 23, 4),
(13, 22, 4),
(13, 21, 4),
(13, 20, 4),
(13, 19, 4),
(13, 18, 4),
(13, 26, 4),
(14, 5, 5),
(14, 6, 5),
(14, 7, 5),
(14, 13, 5),
(14, 15, 5),
(14, 16, 5),
(15, 2, 1),
(15, 36, 1),
(15, 39, 1),
(15, 42, 1),
(15, 43, 1),
(15, 27, 1),
(15, 5, 1),
(15, 6, 1),
(15, 7, 1),
(15, 13, 1),
(15, 15, 1),
(15, 16, 1),
(15, 47, 1),
(15, 46, 1),
(15, 28, 1),
(15, 29, 1),
(15, 30, 1),
(15, 31, 1),
(15, 32, 1),
(15, 33, 1),
(15, 34, 1),
(15, 17, 1),
(15, 25, 1),
(15, 24, 1),
(15, 23, 1),
(15, 22, 1),
(15, 21, 1),
(15, 20, 1),
(15, 19, 1),
(15, 18, 1),
(15, 26, 1),
(16, 2, 1),
(16, 36, 1),
(16, 39, 1),
(16, 42, 1),
(16, 43, 1),
(16, 27, 1),
(16, 5, 1),
(16, 6, 1),
(16, 7, 1),
(16, 13, 1),
(16, 15, 1),
(16, 16, 1),
(16, 47, 1),
(16, 46, 1),
(16, 33, 1),
(16, 32, 1),
(16, 30, 1),
(16, 29, 1),
(16, 31, 1),
(16, 28, 1),
(16, 34, 1),
(16, 24, 1),
(16, 20, 1),
(16, 21, 1),
(16, 26, 1),
(16, 23, 1),
(16, 18, 1),
(16, 25, 1),
(16, 17, 1),
(16, 22, 1),
(16, 19, 1),
(17, 2, 1),
(17, 36, 1),
(17, 39, 1),
(17, 42, 1),
(17, 43, 1),
(17, 27, 1),
(17, 5, 1),
(17, 6, 1),
(17, 7, 1),
(17, 13, 1),
(17, 15, 1),
(17, 16, 1),
(17, 47, 1),
(17, 46, 1),
(17, 33, 1),
(17, 32, 1),
(17, 30, 1),
(17, 29, 1),
(17, 31, 1),
(17, 28, 1),
(17, 34, 1),
(17, 24, 1),
(17, 20, 1),
(17, 21, 1),
(17, 26, 1),
(17, 23, 1),
(17, 18, 1),
(17, 25, 1),
(17, 17, 1),
(17, 22, 1),
(17, 19, 1),
(18, 2, 1),
(18, 36, 1),
(18, 39, 1),
(18, 42, 1),
(18, 43, 1),
(18, 27, 1),
(18, 5, 1),
(18, 6, 1),
(18, 7, 1),
(18, 13, 1),
(18, 15, 1),
(18, 16, 1),
(18, 47, 1),
(18, 46, 1),
(18, 33, 1),
(18, 32, 1),
(18, 30, 1),
(18, 29, 1),
(18, 31, 1),
(18, 28, 1),
(18, 34, 1),
(18, 24, 1),
(18, 20, 1),
(18, 21, 1),
(18, 26, 1),
(18, 23, 1),
(18, 18, 1),
(18, 25, 1),
(18, 17, 1),
(18, 22, 1),
(18, 19, 1),
(19, 2, 1),
(19, 36, 1),
(19, 39, 1),
(19, 42, 1),
(19, 43, 1),
(19, 27, 1),
(19, 5, 1),
(19, 6, 1),
(19, 7, 1),
(19, 13, 1),
(19, 15, 1),
(19, 16, 1),
(19, 47, 1),
(19, 46, 1),
(19, 33, 1),
(19, 32, 1),
(19, 30, 1),
(19, 29, 1),
(19, 31, 1),
(19, 28, 1),
(19, 34, 1),
(19, 24, 1),
(19, 20, 1),
(19, 21, 1),
(19, 26, 1),
(19, 23, 1),
(19, 18, 1),
(19, 25, 1),
(19, 17, 1),
(19, 22, 1),
(19, 19, 1),
(19, 48, 1),
(2, 48, 1),
(3, 48, 2),
(17, 48, 1),
(4, 48, 1),
(5, 48, 2),
(6, 48, 3),
(8, 48, 1),
(18, 48, 1),
(16, 48, 1),
(10, 48, 1),
(11, 48, 2),
(12, 48, 3),
(13, 48, 4),
(15, 48, 1)";

$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_blocks_weight` (`bid`, `func_id`, `weight`) VALUES
(20, 2, 1),
(20, 36, 1),
(20, 39, 1),
(20, 42, 1),
(20, 43, 1),
(20, 27, 1),
(20, 5, 1),
(20, 6, 1),
(20, 7, 1),
(20, 13, 1),
(20, 15, 1),
(20, 16, 1),
(20, 47, 1),
(20, 46, 1),
(20, 33, 1),
(20, 32, 1),
(20, 30, 1),
(20, 29, 1),
(20, 31, 1),
(20, 28, 1),
(20, 34, 1),
(20, 48, 1),
(20, 24, 1),
(20, 20, 1),
(20, 21, 1),
(20, 26, 1),
(20, 23, 1),
(20, 18, 1),
(20, 25, 1),
(20, 17, 1),
(20, 22, 1),
(20, 19, 1)";

$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_blocks_weight` (`bid`, `func_id`, `weight`) VALUES
(16, 35, 1),
(10, 35, 1),
(11, 35, 2),
(12, 35, 3),
(13, 35, 4),
(15, 35, 1),
(18, 35, 1),
(17, 35, 1),
(19, 35, 1),
(2, 35, 1),
(3, 35, 2),
(4, 35, 1),
(5, 35, 2),
(6, 35, 3),
(8, 35, 1),
(20, 35, 1)";

$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_blocks_weight` (`bid`, `func_id`, `weight`) VALUES
(16, 50, 1),
(10, 50, 1),
(11, 50, 2),
(12, 50, 3),
(13, 50, 4),
(15, 50, 1),
(18, 50, 1),
(17, 50, 1),
(19, 50, 1),
(2, 50, 1),
(3, 50, 2),
(4, 50, 1),
(5, 50, 2),
(6, 50, 3),
(8, 50, 1),
(20, 50, 1)";

$disable_site_content = "Notre site est fermé temporairement pour la maintenance. Veuillez revenir plus tard. Merci!";
$copyright = "Veuillez citer le lien vers l&#039;article original si vous le reproduisez sur un autre site. Merci.";
$site_description = "NUKEVIET CMS 3.0 Developé par Vinades.,Jsc";

$sql_create_table[] = "UPDATE `" . $db_config['prefix'] . "_config` SET `config_value` =  " . $db->dbescape_string( $site_description ) . " WHERE `module` =  'global' AND `config_name` = 'site_description' AND `lang`='fr'";
$sql_create_table[] = "UPDATE `" . $db_config['prefix'] . "_config` SET `config_value` =  " . $db->dbescape_string( $disable_site_content ) . " WHERE `module` =  'global' AND `config_name` = 'disable_site_content' AND `lang`='fr'";

$array_cron_name = array();
$array_cron_name['cron_online_expired_del'] = 'Supprimer les anciens registres du status en ligne dans la base de données';
$array_cron_name['cron_dump_autobackup'] = 'Sauvegarder automatique la base de données';
$array_cron_name['cron_auto_del_temp_download'] = 'Supprimer les fichiers temporaires du répertoire tmp';
$array_cron_name['cron_del_ip_logs'] = 'Supprimer les fichiers ip_logs expirés';
$array_cron_name['cron_auto_del_error_log'] = 'Supprimer les fichiers error_log expirés';
$array_cron_name['cron_auto_sendmail_error_log'] = 'Envoyer à l\'administrateur l\'e-mail des notifications d\'erreurs';
$array_cron_name['cron_ref_expired_del'] = 'Supprimer les referers expirés';
$array_cron_name['cron_siteDiagnostic_update'] = 'Mise à jour du site de diagnostic';
$array_cron_name['cron_auto_check_version'] = 'Vérifier la version NukeViet';

$result = $db->sql_query( "SELECT `id`, `run_func` FROM `" . $db_config['prefix'] . "_cronjobs` ORDER BY `id` ASC" );
while( list( $id, $run_func ) = $db->sql_fetchrow( $result ) )
{
	$cron_name = ( isset( $array_cron_name[$run_func] ) ) ? $array_cron_name[$run_func] : $run_func;
	$sql_create_table[] = "UPDATE `" . $db_config['prefix'] . "_cronjobs` SET `" . $lang_data . "_cron_name` =  " . $db->dbescape_string( $cron_name ) . " WHERE `id`=" . $id;
}
$db->sql_freeresult();

$sql_create_table[] = "UPDATE `" . $db_config['prefix'] . "_config` SET `config_value` = 'modern' WHERE `lang` = '" . $lang_data . "' AND `module` = 'global' AND `config_name` = 'site_theme'";

$result = $db->sql_query( "SELECT * FROM `" . $db_config['prefix'] . "_" . $lang_data . "_modules` where `title`='news'" );
if( $db->sql_numrows( $result ) )
{
	$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_news_cat` VALUES
		(1, 0, 'News', '', 'News', '', '', '', 1, 1, 0, 'viewcat_page_new', 3, '5,6,7', 1, 3, '', '', 1280644983, 1280927178, 0, ''), 
		(2, 0, 'Produits', '', 'Produits', '', '', '', 2, 5, 0, 'viewcat_page_new', 0, '', 1, 3, '', '', 1280644996, 1280644996, 0, ''), 
		(3, 0, 'Partenaires', '', 'Partenaires', '', '', '', 3, 6, 0, 'viewcat_page_new', 0, '', 1, 3, '', '', 1280645023, 1280645023, 0, ''), 
		(4, 0, 'Recrutement', '', 'Recruitement', '', '', '', 4, 7, 0, 'viewcat_page_new', 0, '', 1, 3, '', '', 1280649352, 1280649900, 0, ''), 
		(5, 1, 'News Interne', '', 'News-Interne', '', '', '', 1, 2, 1, 'viewcat_page_new', 0, '', 1, 3, '', '', 1280927318, 1280927318, 0, ''), 
		(6, 1, 'Nouvelles Technologies', '', 'Nouvelles-Technologies', '', '', '', 2, 3, 1, 'viewcat_page_new', 0, '', 1, 3, '', '', 1280927364, 1280927364, 0, ''), 
		(7, 1, 'Espace presse', '', 'Espace-presse', '', '', '', 3, 4, 1, 'viewcat_page_new', 0, '', 1, 3, '', '', 1280928740, 1280928740, 0, '')";

	$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_news_rows` VALUES
		(1, 1, '1,2', 0, 1, '', 0, 1280645699, 1280751776, 1, 1280645640, 0, 2, 'Nukeviet 3.0', 'Nukeviet-3-0', 'NukeViet 3 est une nouvelle génération de Système de Gestion de Contenu développée par les Vietnamiens. Pour la première fois au Vietnam, un noyau de Open Source ouverte est investi professionnelement en financement, en ressources humaines et en temps. Le résultat est que 100% de ligne de code de NukeViet est écrit entièrement neuf. Nukeviet 3.0 utilise XHTML, CSS et jQuery avec Xtemplate permettant une application souple de Ajax, même au niveau de noyau.', 'nukeviet3.jpg', '', 'thumb/nukeviet3.jpg|block/nukeviet3.jpg', 1, 2, 1, 2, 0, 0, 0, ''),
		(2, 2, '2', 0, 1, '', 0, 1280645876, 1280751372, 1, 1280645820, 0, 2, 'NukeViet', 'NukeViet', 'NukeViet est un système de gestion de contenu open source. Les utilisateurs l’appellent habituellement Portail parce qu&#039;il est capable d&#039;intégrer plusieurs applications sur le Web. Nguyễn Anh Tú, un ex-étudiant vietnamien en Russie, avec la communauté a développé NukeViet en une application purement vietnamienne en basant sur PHP-Nuke.', 'screenshot.jpg', '', 'thumb/screenshot.jpg|block/screenshot.jpg', 1, 2, 1, 3, 0, 0, 0, ''),
		(3, 3, '3', 0, 1, '', 0, 1280646202, 1280751407, 1, 1280646180, 0, 2, 'VINADES', 'VINADES', 'Pour professionaliser la publication de NukeViet,  l&#039;administration de NukeViet a décidé de créer une société spécialisant la  gestion de NukeViet avec la raison sociale en vietnamien “Công ty cổ phần Phát triển Nguồn mở Việt Nam”, en anglais &quot;VIET NAM OPEN SOURCE DEVELOPMENT JOINT STOCK COMPANY&quot; et en abrégé VINADES.,JSC.', 'nangly.jpg', '', 'thumb/nangly.jpg|block/nangly.jpg', 1, 2, 1, 3, 0, 0, 0, 'de nukeviet'),
		(4, 4, '4', 0, 1, '', 0, 1280650419, 1280751748, 1, 1280650380, 0, 2, 'Recrutement et la formation des enseignants', 'Recrutement-et-la-formation-des-enseignants', 'A l’issue d’une série de consultations avec les organisations représentatives des personnels de l’éducation nationale et de l’enseignement supérieur sur la réforme du recrutement et de la formation des enseignants, le ministre de l’Éducation nationale et la ministre de l’Enseignement supérieur et de la Recherche apportent plusieurs éléments d’information complémentaires.', 'hoptac.jpg', '', 'thumb/hoptac.jpg|block/hoptac.jpg', 1, 2, 1, 4, 0, 0, 0, '')";

	$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_news_bodyhtml_1` VALUES
		(1, '<p> Profiter les fruits de Open Source, mais chaque ligne de code de NukeViet est écrit manuellement. NukeViet 3 n&#039;utilise aucune plateforme. Cela signifie que Nukeviet 3 est complètement indépendant dans son développemnt. Il est très facile à lire, à comprendre le code de NukeViet pour programmer tout seul si vous avez les connaissances de base sur PHP et MySQL. NukeViet 3.0 est complètement ouvert et facile à apprendre pour tous ceux qui veulent étudier le code de NukeViet.</p><p> Hériter la simplicité de Nukeviet mais NukeViet 3 n&#039;oublie pas de se renouveller. Le système de Nukeviet 3 supporte le multi-noyau du module. Nous appelons cela la technologie de virtualisation de module. Cette technologie permet aux utilisateurs de créer automatiquement de milliers de modules sans toucher une seule ligne de code. Le module né de cette technologie est appelé module virtuel. Il est cloné à partir de n&#039;importe quel module du système de NukeViet si ce module-ci permet la création des modules virtuels.</p><p> NukeViet 3 prend en charge l&#039;installation automatique de modules, de blocks, de thèmes dans la section d&#039;administration, les utilisateurs peuvent installer le module sans faire de tâches complexes. NukeViet 3.0 permet également le paquetage des modules pour partager aux autres utilisateus.</p><p> Le multi-langage de NukeViet 3 est parfait avec le multi-langage de l&#039;interface et celui de données. NukeViet 3.0 supporte aux administrateurs de créer facilement de nouvelles langues pour le site. Le paquetage des fichiers de langue est également supporté pour faciliter la contribution du travai à la communauté.</p>', '', 1, 0, 1, 1, 1), 
		(2, '<p> Similaire à PHP-Nuke, NukeViet est écrit en langage PHP et utilise la base de données MySQL, permet aux utilisateurs de publier, de gérer facilement leur contenu sur Internet ou Intranet.</p><p> <strong>* Fonctionnalités de base de NukeViet: </strong></p><p> - News: Gestion d’articles: créer les articles multi-niveau, générer la page d’impression, permettre le téléchargement, les commentaires.</p><p> -&nbsp; Download: Gestion de téléchargement des fichier</p><p> - Vote: sondage</p><p> - Contact</p><p> -&nbsp; Search: Rechercher</p><p> -&nbsp; RSS</p><p> <strong>* Caractéristiques: </strong></p><p> - Supporter le multi-langage</p><p> - Permettre le changement de l’interface (theme)</p><p> - Monter le pare-feu pour limiter DDOS ...</p><p> Nukeviet est utilisé dans de nombreux sites Web, de sites personnels aux sites professionnels. Il offre de nombreux services et applications grâce à la capacité d&#039;accroître la fonctionnalité en installant des modules, blocks additionnels ... Cependant, Nukeviet est utilisé principalement pour les sites d’actualités vietnamiens par ce que son module News conforme bien aux exigences et habitudes des Vietnamiens. Il est très facile d’installer, de gérer Nukeviet, même avec les débutants, il est donc un système favorable des amateurs.</p><p> NukeViet est open source, et totalement gratuit pour tout de monde de tous les pays. Toutefois, les Vietnamiens sont les utilisateurs principales en raison des caractéristiques de la code source (provenant de PHP-Nuke) et de la politique des développeurs &quot;Système de Portail Pour les Vietnamiens&quot;.</p>', '', 1, 0, 1, 1, 1), 
		(3, '<p> Cette société est ouverte officiellement au&nbsp; 25-2-2010 avec le bureau à&nbsp; Chambre 1805 – CT2 Nang Huong building, 583 Nguyen Trai, Hanoi, Vietnam. Son but est de développer et de diffuser NukeViet au Vietnam.<br  /> <br  /> D&#039;après M. Nguyễn Anh Tú, président de VINADES, cette société développera le source de NukeViet sous forme open source, professionnel, et totalement gratuit selon l&#039;esprit mondial de open source.<br  /> <br  /> NukeViet est un système de gestion de contenu open source (Open Source Content Management System) purement vietnamien développé à la base de PHP-Nuke et base de données MySQL. Les utilisateurs l&#039;appellent habituellement Portail par ce qu&#039;ils puissent intégrer de multiples applications permettant la publication et la gestion facile de contenu sur l&#039;internet ou sur l&#039;intranet.</p><p> NukeViet peut fournir plusieurs services et appliations grace aux modules, blocks... L&#039;installation, la gestion de NukeViet 3 est très facile,&nbsp; même avec les débutants.</p><p> Depuis quelques années, NukeViet est devenu une application Open Source tres familière de la communauté informatique du Vietnam. Nukeviet est utilisé dans presque toutes les domaines, de l&#039;actualité, de la commerce électronique, de site personnel aux site professionel.</p><p> Pour avoir les details plus amples sur NukeViet, veuillez consulter le site http://nukeviet.vn.</p>', '', 1, 0, 1, 1, 1), 
		(4, '<p> Ils précisent, notamment, les modalités concrètes de concertation qui conduiront à la mise en place de la réforme définitive au cours de l’année 2010/2011. Le processus de concertation avec les organisations représentatives reposera notamment sur trois groupes de travail ch@rgés d’étudier :<br  /> <br  /> &nbsp;&nbsp;&nbsp; * Les concours de recrutement<br  /> &nbsp;&nbsp;&nbsp; * Le cadrage des masters et leur articulation avec les concours<br  /> &nbsp;&nbsp;&nbsp; * L’organisation et le contenu de la période de formation continuée pendant l’année de fonctionnaire stagiaire à l’issue du concours<br  /> <br  /> Une commission de concertation sur la réforme du recrutement et de la formation sera également mise en place avec des acteurs universitaires. Le recteur Marois et le président Filatre en assureront la coprésidence. Ils feront très rapidement des propositions aux ministres sur la composition et le fonctionnement de cette commission qui consultera régulièrement les organisations représentatives.<br  /> <br  /> Les ministres ont également détaillé les conditions de mise en oeuvre du processus de mastérisation de la formation des enseignants et des conseillers principaux d’éducation (C.P.E.), qui sera engagé dès l’année prochaine.<br  /> <br  /> Ils confirment que, pour la session 2010, les contenus des concours resteront en l’état. Par ailleurs, pour s’inscrire aux concours de la session 2010, les étudiants devront :<br  /> <br  /> &nbsp;&nbsp;&nbsp; * Soit déjà être titulaires d’un master ou inscrits en M2 à la rentrée universitaire 2009 ;<br  /> &nbsp;&nbsp;&nbsp; * Soit, à titre exceptionnel et dérogatoire, pour la seule session 2010 des concours :<br  /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - avoir été présents aux épreuves d’admissibilité de la session 2009<br  /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - ou bien, être inscrits en M1 dans une composante universitaire à la rentrée 2009.<br  /> <br  /> Pour l’année transitoire 2009 - 2010 l’inscription en I.U.F.M. vaudra également inscription en M1 par convention avec les universités afin de favoriser le processus de mastérisation. En cas de réussite à un concours de la session 2010, le bénéfice du concours sera garanti pendant un an à ces candidats inscrits en M1. Ils seront recrutés comme enseignant stagiaire pour la rentrée scolaire 2011 sous réserve de l’obtention de leur M2 à l’issue de l’année universitaire 2010-2011.<br  /> <br  /> Dès septembre 2009, des stages de pratique accompagnée ou en responsabilité rémunérés seront mis en place afin d’engager le processus de préprofessionnalisation lié à la mastérisation.<br  /> <br  /> Dès la prochaine rentrée universitaire, les étudiants se destinant au métier d’enseignant pourront également bénéficier d’un dispositif d’aides complémentaires mis en oeuvre par le ministère de l’Éducation Nationale.<br  /> <br  /> A la rentrée 2010, un tiers de l’obligation de service des nouveaux enseignants, recrutés lors de la session 2010 des concours, sera consacré à une formation continue renforcée, prenant la forme d’un tutorat et d’une formation universitaire à visée disciplinaire ou professionnelle.<br  /> <br  /> Enfin, la discussion sur la revalorisation du salaire des nouveaux enseignants sera conduite en parallèle pour être applicable aux lauréats des concours de la session 2010.</p>', '', 1, 0, 1, 1, 1)";

	$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_news_bodytext` VALUES
		(1, ' Profiter les fruits de Open Source, mais chaque ligne de code de NukeViet est écrit manuellement. NukeViet 3 n&#039;utilise aucune plateforme. Cela signifie que Nukeviet 3 est complètement indépendant dans son développemnt. Il est très facile à lire, à comprendre le code de NukeViet pour programmer tout seul si vous avez les connaissances de base sur PHP et MySQL. NukeViet 3.0 est complètement ouvert et facile à apprendre pour tous ceux qui veulent étudier le code de NukeViet. Hériter la simplicité de Nukeviet mais NukeViet 3 n&#039;oublie pas de se renouveller. Le système de Nukeviet 3 supporte le multi-noyau du module. Nous appelons cela la technologie de virtualisation de module. Cette technologie permet aux utilisateurs de créer automatiquement de milliers de modules sans toucher une seule ligne de code. Le module né de cette technologie est appelé module virtuel. Il est cloné à partir de n&#039;importe quel module du système de NukeViet si ce module-ci permet la création des modules virtuels. NukeViet 3 prend en c-harge l&#039;installation automatique de modules, de blocks, de thèmes dans la section d&#039;administration, les utilisateurs peuvent installer le module sans faire de tâches complexes. NukeViet 3.0 permet également le paquetage des modules pour partager aux autres utilisateus. Le multi-langage de NukeViet 3 est parfait avec le multi-langage de l&#039;interface et celui de données. NukeViet 3.0 supporte aux administrateurs de créer facilement de nouvelles langues pour le site. Le paquetage des fichiers de langue est également supporté pour faciliter la contribution du travai à la communauté.'),
		(2, ' Similaire à PHP-Nuke, NukeViet est écrit en langage PHP et utilise la base de données MySQL, permet aux utilisateurs de publier, de gérer facilement leur contenu sur Internet ou Intranet. * Fonctionnalités de base de NukeViet: - News: Gestion d’articles: créer les articles multi-niveau, générer la page d’impression, permettre le téléc-hargement, les commentaires. - Download: Gestion de téléc-hargement des fichier - Vote: sondage - Contact - Search: Rechercher - RSS * Caractéristiques: - Supporter le multi-langage - Permettre le changement de l’interface (theme) - Monter le pare-feu pour limiter DDOS ... Nukeviet est utilisé dans de nombreux sites Web, de sites personnels aux sites professionnels. Il offre de nombreux services et applications grâce à la capacité d&#039;accroître la fonctionnalité en installant des modules, blocks additionnels ... Cependant, Nukeviet est utilisé principalement pour les sites d’actualités vietnamiens par ce que son module News conforme bien aux exigences et habitudes des Vietnamiens. Il est très facile d’installer, de gérer Nukeviet, même avec les débutants, il est donc un système favorable des amateurs. NukeViet est open source, et totalement gratuit pour tout de monde de tous les pays. Toutefois, les Vietnamiens sont les utilisateurs principales en raison des caractéristiques de la code source (provenant de PHP-Nuke) et de la politique des développeurs \"Système de Portail Pour les Vietnamiens\".'),
		(3, ' Cette société est ouverte officiellement au 25-2-2010 avec le bureau à Chambre 1805 – CT2 Nang Huong building, 583 Nguyen Trai, Hanoi, Vietnam. Son but est de développer et de diffuser NukeViet au Vietnam. D&#039;après M. Nguyễn Anh Tú, président de VINADES, cette société développera le source de NukeViet sous forme open source, professionnel, et totalement gratuit selon l&#039;esprit mondial de open source. NukeViet est un système de gestion de contenu open source (Open Source Content Management System) purement vietnamien développé à la base de PHP-Nuke et base de données MySQL. Les utilisateurs l&#039;appellent habituellement Portail par ce qu&#039;ils puissent intégrer de multiples applications permettant la publication et la gestion facile de contenu sur l&#039;internet ou sur l&#039;intranet. NukeViet peut fournir plusieurs services et appliations grace aux modules, blocks... L&#039;installation, la gestion de NukeViet 3 est très facile, même avec les débutants. Depuis quelques années, NukeViet est devenu une application Open Source tres familière de la communauté informatique du Vietnam. Nukeviet est utilisé dans presque toutes les domaines, de l&#039;actualité, de la commerce électronique, de site personnel aux site professionel. Pour avoir les details plus amples sur NukeViet, veuillez consulter le site http://nukeviet.vn.'),
		(4, ' Ils précisent, notamment, les modalités concrètes de concertation qui conduiront à la mise en place de la réforme définitive au cours de l’année 2010/2011. Le processus de concertation avec les organisations représentatives reposera notamment sur trois groupes de travail ch@rgés d’étudier : * Les concours de recrutement * Le cadrage des masters et leur articulation avec les concours * L’organisation et le contenu de la période de formation continuée pendant l’année de fonctionnaire stagiaire à l’issue du concours Une commission de concertation sur la réforme du recrutement et de la formation sera également mise en place avec des acteurs universitaires. Le recteur Marois et le président Filatre en assureront la coprésidence. Ils feront très rapidement des propositions aux ministres sur la composition et le fonctionnement de cette commission qui consultera régulièrement les organisations représentatives. Les ministres ont également détaillé les conditions de mise en oeuvre du processus de mastérisation de la formation des enseignants et des conseillers principaux d’éducation (C.P.E.), qui sera engagé dès l’année prochaine. Ils confirment que, pour la session 2010, les contenus des concours resteront en l’état. Par ailleurs, pour s’inscrire aux concours de la session 2010, les étudiants devront : * Soit déjà être titulaires d’un master ou inscrits en M2 à la rentrée universitaire 2009 ; * Soit, à titre exceptionnel et dérogatoire, pour la seule session 2010 des concours : - avoir été présents aux épreuves d’admissibilité de la session 2009 - ou bien, être inscrits en M1 dans une composante universitaire à la rentrée 2009. Pour l’année transitoire 2009 - 2010 l’inscription en I.U.F.M. vaudra également inscription en M1 par convention avec les universités afin de favoriser le processus de mastérisation. En cas de réussite à un concours de la session 2010, le bénéfice du concours sera garanti pendant un an à ces candidats inscrits en M1. Ils seront recrutés comme enseignant stagiaire pour la rentrée scolaire 2011 sous réserve de l’obtention de leur M2 à l’issue de l’année universitaire 2010-2011. Dès septembre 2009, des stages de pratique accompagnée ou en responsabilité rémunérés seront mis en place afin d’engager le processus de préprofessionnalisation lié à la mastérisation. Dès la prochaine rentrée universitaire, les étudiants se destinant au métier d’enseignant pourront également bénéficier d’un dispositif d’aides complémentaires mis en oeuvre par le ministère de l’Éducation Nationale. A la rentrée 2010, un tiers de l’obligation de service des nouveaux enseignants, recrutés lors de la session 2010 des concours, sera consacré à une formation continue renforcée, prenant la forme d’un tutorat et d’une formation universitaire à visée disciplinaire ou professionnelle. Enfin, la discussion sur la revalorisation du salaire des nouveaux enseignants sera conduite en parallèle pour être applicable aux lauréats des concours de la session 2010.')";

	$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_news_block_cat` (`bid`, `adddefault`, `number`, `title`, `alias`, `image`, `thumbnail`, `description`, `weight`, `keywords`, `add_time`, `edit_time`) VALUES
		(1, 0, 4, 'Populairs', 'Populairs', '', '', 'Block Populairs', 1, '', 1279945710, 1279956943),
		(2, 1, 4, 'Récents', 'Recents', '', '', 'Block Récents', 2, '', 1279945725, 1279956445)";

	$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_news_block` (`bid`, `id`, `weight`) VALUES
		(1, 2, 2),
		(1, 1, 1)";

	$sql_create_table[] = "UPDATE `" . $db_config['prefix'] . "_config` SET `config_value` =  " . $db->dbescape_string( $copyright ) . " WHERE `module` =  'news' AND `config_name` = 'copyright' AND `lang`='fr'";
	$sql_create_table[] = "UPDATE `" . $db_config['prefix'] . "_config` SET `config_value` =  'news' WHERE `module` =  'global' AND `config_name` = 'site_home_module' AND `lang`='" . $lang_data . "'";
}

$result = $db->sql_query( "SELECT * FROM `" . $db_config['prefix'] . "_" . $lang_data . "_modules` where `title`='voting'" );
if( $db->sql_numrows( $result ) )
{
	$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_voting` VALUES
		(1, 'Qu&#039;est ce que NukeViet 3.0?', '', 1, 1, 0, '0', 1275318563, 0, 1)";

	$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_voting_rows` VALUES
		(1, 1, 'Une code source de web tout neuve','', 0), 
		(2, 1, 'Open source, libre et gratuit','', 0), 
		(3, 1, 'Utilise xHTML, CSS et supporte Ajax','', 0), 
		(4, 1, 'Toutes ces réponses','', 1)";
}

$result = $db->sql_query( "SELECT * FROM `" . $db_config['prefix'] . "_" . $lang_data . "_modules` where `title`='about'" );
if( $db->sql_numrows( $result ) )
{
	$sql_create_table[] = "INSERT INTO `" . $db_config['prefix'] . "_" . $lang_data . "_about` (`id`, `title`, `alias`, `bodytext`, `keywords`, `weight`, `admin_id`, `add_time`, `edit_time`, `status`) VALUES
		(1, 'Qu’est ce que Nukeviet?', 'Qu-est-ce-que-Nukeviet', '<p> NukeViet est un système de gestion de contenu open source. Les utilisateurs l’appellent habituellement Portail parce qu&#039;il est capable d&#039;intégrer plusieurs applications sur le Web. Nguyễn Anh Tú, un ex-étudiant vietnamien en Russie, avec la communauté a développé NukeViet en une application purement vietnamienne en basant sur PHP-Nuke. Similaire à PHP-Nuke, NukeViet est écrit en langage PHP et utilise la base de données MySQL, permet aux utilisateurs de publier, de gérer facilement leur contenu sur Internet ou Intranet.<br  />  </p><p> <strong>* Fonctionnalités de base de NukeViet: </strong></p><p> - News: Gestion d’articles: créer les articles multi-niveau, générer la page d’impression, permettre le téléchargement, les commentaires.</p><p> -&nbsp; Download: Gestion de téléchargement des fichier</p><p> - Vote: sondage</p><p> - Contact</p><p> -&nbsp; Search: Rechercher</p><p> -&nbsp; RSS</p><p> <strong>* Caractéristiques: </strong></p><p> - Supporter le multi-langage</p><p> - Permettre le changement de l’interface (theme)</p><p> - Monter le pare-feu pour limiter DDOS ...</p><p> Nukeviet est utilisé dans de nombreux sites Web, de sites personnels aux sites professionnels. Il offre de nombreux services et applications grâce à la capacité d&#039;accroître la fonctionnalité en installant des modules, blocks additionnels ... Cependant, Nukeviet est utilisé principalement pour les sites d’actualités vietnamiens par ce que son module News conforme bien aux exigences et habitudes des Vietnamiens. Il est très facile d’installer, de gérer Nukeviet, même avec les débutants, il est donc un système favorable des amateurs.</p><p> NukeViet est open source, et totalement gratuit pour tout de monde de tous les pays. Toutefois, les Vietnamiens sont les utilisateurs principales en raison des caractéristiques de la code source (provenant de PHP-Nuke) et de la politique des développeurs &quot;Système de Portail Pour les Vietnamiens&quot;.</p>', '', 1, 1, 1280634933, 1280634933, 1), 
		(2, 'Introduction de NukeViet 3', 'Introduction-de-NukeViet-3', '<p> NukeViet 3 est une nouvelle génération de Système de Gestion de Contenu développée par les Vietnamiens. Pour la première fois au Vietnam, un noyau de Open Source ouverte est investi professionnelement en financement, en ressources humaines et en temps. Le résultat est que 100% de ligne de code de NukeViet est écrit entièrement neuf. Nukeviet 3.0 utilise XHTML, CSS et jQuery avec Xtemplate permettant une application souple de Ajax, même au niveau de noyau.</p><p> Profiter les fruits de Open Source, mais chaque ligne de code de NukeViet est écrit manuellement. NukeViet 3 n&#039;utilise aucune plateforme. Cela signifie que Nukeviet 3 est complètement indépendant dans son développemnt. Il est très facile à lire, à comprendre le code de NukeViet pour programmer tout seul si vous avez les connaissances de base sur PHP et MySQL. NukeViet 3.0 est complètement ouvert et facile à apprendre pour tous ceux qui veulent étudier le code de NukeViet.</p><p> Hériter la simplicité de Nukeviet mais NukeViet 3 n&#039;oublie pas de se renouveller. Le système de Nukeviet 3 supporte le multi-noyau du module. Nous appelons cela la technologie de virtualisation de module. Cette technologie permet aux utilisateurs de créer automatiquement de milliers de modules sans toucher une seule ligne de code. Le module né de cette technologie est appelé module virtuel. Il est cloné à partir de n&#039;importe quel module du système de NukeViet si ce module-ci permet la création des modules virtuels.</p><p> NukeViet 3 prend en charge l&#039;installation automatique de modules, de blocks, de thèmes dans la section d&#039;administration, les utilisateurs peuvent installer le module sans faire de tâches complexes. NukeViet 3.0 permet également le paquetage des modules pour partager aux autres utilisateus.</p><p> Le multi-langage de NukeViet 3 est parfait avec le multi-langage de l&#039;interface et celui de données. NukeViet 3.0 supporte aux administrateurs de créer facilement de nouvelles langues pour le site. Le paquetage des fichiers de langue est également supporté pour faciliter la contribution du travai à la communauté.</p><p> L&#039;histoire de NukeViet sera encore très longue&nbsp; par ce qu’une variété de fonctionnalités avancées sont encore en cours d&#039;élaboration.</p><p> Utilisez et diffusez NukeViet 3 pour jouir les récents fruits de la technologies de web open source.</p><p> Enfin, NukeViet 3 est un cadeau que VINADES voudrait envoyer à la communauté pour remercier son soutient. NukeViet retourne maintenant à la communauté dans l’espoir à son développement continu.</p><p> Si vous intéressez à NukeViet, n’hésitez pas à nous joindre au Forum de NukeViet.Vn.</p>', '', 3, 1, 1280637520, 1280637520, 1), 
		(3, 'Ouverture de VINADES', 'Ouverture-de-VINADES', '<p> Depuis quelques années, NukeViet est devenu une application Open Source tres familière de la communauté informatique du Vietnam. Étant donnée qu&#039;il n&#039;y a pas encore les activités officielles, Nukeviet est utilisé dans presque toutes les domaines, de l&#039;actualité, de la commerce électronique, de site personnel aux site professionle.<br  />  </p><p> Pour professionaliser la publication de NukeViet,&nbsp; l&#039;administration de NukeViet a décidé de créer une société spécialisant la&nbsp; gestion de NukeViet avec la raison sociale en vietnamien “Công ty cổ phần Phát triển Nguồn mở Việt Nam”, en anglais &quot;VIET NAM OPEN SOURCE DEVELOPMENT JOINT STOCK COMPANY&quot; et en abrégé VINADES.,JSC. Cette société est ouverte officiellement au&nbsp; 25-2-2010 avec le bureau à&nbsp; Chambre 1805 – CT2 Nang Huong building, 583 Nguyen Trai, Hanoi, Vietnam. Son but est de développer et de diffuser NukeViet au Vietnam.<br  /> <br  /> D&#039;après M. Nguyễn Anh Tú, président de VINADES, cette société développera le source de NukeViet sous forme open source, professionnel, et totalement gratuit selon l&#039;esprit mondial de open source.<br  /> <br  /> NukeViet est un système de gestion de contenu open source (Open Source Content Management System) purement vietnamien développé à la base de PHP-Nuke et base de données MySQL. Les utilisateurs l&#039;appellent habituellement Portail par ce qu&#039;ils puissent intégrer de multiples applications permettant la publication et la gestion facile de contenu sur l&#039;internet ou sur l&#039;intranet.</p><p> <br  /> NukeViet peut fournir plusieurs services et appliations grace aux modules, blocks... L&#039;installation, la gestion de NukeViet 3 est très facile,&nbsp; même avec les débutants.</p><p> Pour avoir les details plus amples sur NukeViet, veuillez consulter le site http://nukeviet.vn.</p>', '', 2, 1, 1280637944, 1280637944, 1)";
}

?>