<?php

/**
 * @Project NUKEVIET 3.0
 * @Author VINADES.,JSC (contact@vinades.vn)
 * @copyright 2009
 * @createdate 10/03/2010 10:51
 */
if ( ! defined( 'NV_IS_FILE_MODULES' ) ) die( 'Stop!!!' );

$sql_drop_module = array();

$sql_drop_module[] = "DELETE FROM `" . NV_USERS_GLOBALTABLE . "_question` WHERE `lang`=" . $db->dbescape( $lang );
$sql_drop_module[] = "DELETE FROM `" . NV_USERS_GLOBALTABLE . "_config` WHERE `config`=" . $db->dbescape( "siteterms_" . $lang );

$sql_create_module = $sql_drop_module;
if ( $lang == "vi" )
{
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'Bạn thích môn thể thao nào nhất', '" . $lang . "', 1, 1274840238, 1274840238)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'Món ăn mà bạn yêu thích', '" . $lang . "', 2, 1274840250, 1274840250)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'Thần tượng điện ảnh của bạn', '" . $lang . "', 3, 1274840257, 1274840257)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'Bạn thích nhạc sỹ nào nhất', '" . $lang . "', 4, 1274840264, 1274840264)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'Quê ngoại của bạn ở đâu', '" . $lang . "', 5, 1274840270, 1274840270)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'Tên cuốn sách &quot;gối đầu giường&quot;', '" . $lang . "', 6, 1274840278, 1274840278)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'Ngày lễ mà bạn luôn mong đợi', '" . $lang . "', 7, 1274840285, 1274840285)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_config` (`config`, `content`, `edit_time`) VALUES ('siteterms_vi', '<p> Để trở thành thành viên, bạn phải cam kết đồng ý với các điều khoản dưới đây. Chúng tôi có thể thay đổi lại những điều khoản này vào bất cứ lúc nào và chúng tôi sẽ cố gắng thông báo đến bạn kịp thời.<br  /> <br  /> Bạn cam kết không gửi bất cứ bài viết có nội dung lừa đảo, thô tục, thiếu văn hoá; vu khống, khiêu khích, đe doạ người khác; liên quan đến các vấn đề tình dục hay bất cứ nội dung nào vi phạm luật pháp của quốc gia mà bạn đang sống, luật pháp của quốc gia nơi đặt máy chủ của website này hay luật pháp quốc tế. Nếu vẫn cố tình vi phạm, ngay lập tức bạn sẽ bị cấm tham gia vào website. Địa chỉ IP của tất cả các bài viết đều được ghi nhận lại để bảo vệ các điều khoản cam kết này trong trường hợp bạn không tuân thủ.<br  /> <br  /> Bạn đồng ý rằng website có quyền gỡ bỏ, sửa, di chuyển hoặc khoá bất kỳ bài viết nào trong website vào bất cứ lúc nào tuỳ theo nhu cầu công việc.<br  /> <br  /> Đăng ký làm thành viên của chúng tôi, bạn cũng phải đồng ý rằng, bất kỳ thông tin cá nhân nào mà bạn cung cấp đều được lưu trữ trong cơ sở dữ liệu của hệ thống. Mặc dù những thông tin này sẽ không được cung cấp cho bất kỳ người thứ ba nào khác mà không được sự đồng ý của bạn, chúng tôi không chịu trách nhiệm về việc những thông tin cá nhân này của bạn bị lộ ra bên ngoài từ những kẻ phá hoại có ý đồ xấu tấn công vào cơ sở dữ liệu của hệ thống.</p>', 1274757129)";
}
else
{
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'What is the first name of your favorite uncle?', '" . $lang . "', 1, 1274841115, 1274841115)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'whe-re did you meet your spouse', '" . $lang . "', 2, 1274841123, 1274841123)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'What is your oldest cousin&#039;s name?', '" . $lang . "', 3, 1274841131, 1274841131)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'What is your youngest child&#039;s nickname?', '" . $lang . "', 4, 1274841142, 1274841142)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'What is your oldest child&#039;s nickname?', '" . $lang . "', 5, 1274841150, 1274841150)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'What is the first name of your oldest niece?', '" . $lang . "', 6, 1274841158, 1274841158)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'What is the first name of your oldest nephew?', '" . $lang . "', 7, 1274841167, 1274841167)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'What is the first name of your favorite aunt?', '" . $lang . "', 8, 1274841175, 1274841175)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_question` (`qid`, `title`, `lang`, `weight`, `add_time`, `edit_time`) VALUES(NULL, 'whe-re did you spend your honeymoon?', '" . $lang . "', 9, 1274841183, 1274841183)";
    $sql_create_module[] = "INSERT INTO `" . NV_USERS_GLOBALTABLE . "_config` (`config`, `content`, `edit_time`) VALUES ('siteterms_" . $lang . "', '<p style=\"text-align:center;\"> <strong>Website usage terms and conditions – sample template</strong></p><p> Welcome to our website. If you continue to browse and use this website you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern [business name]’s relationship with you in relation to this website.<br  /> The term ‘[business name]’ or ‘us’ or ‘we’ refers to the owner of the website whose registered office is [address]. Our company registration number is [company registration number and place of registration]. The term ‘you’ refers to the user or viewer of our website.<br  /> The use of this website is subject to the following terms of use:<br  /> • The content of the pages of this website is for your general information and use only. It is subject to change without notice.<br  /> • Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.<br  /> • Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.<br  /> • This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.<br  /> • All trademarks reproduced in this website, which are not the property of, or licensed to the operator, are acknowledged on the website.<br  /> • Unauthorised use of this website may give rise to a claim for damages and/or be a criminal offence.<br  /> • fr0m time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).<br  /> • You may not crea-te a link to this website fr0m another website or document without [business name]’s prior written consent.<br  /> • Your use of this website and any dispute arising out of such use of the website is subject to the laws of England, Scotland and Wales.</p>', 1274757617)";
}

?>