window.jQuery&&function(a){if(a.browser.msie)try{document.execCommand("BackgroundImageCache",false,true)}catch(m){}a.fn.rating=function(c){if(this.length==0)return this;if(typeof arguments[0]=="string"){if(this.length>1){var d=arguments;return this.each(function(){a.fn.rating.apply(a(this),d)})}a.fn.rating[arguments[0]].apply(this,a.makeArray(arguments).slice(1)||[]);return this}c=a.extend({},a.fn.rating.options,c||{});a.fn.rating.calls++;this.not(".star-rating-applied").addClass("star-rating-applied").each(function(){var b,
e=a(this),k=(this.name||"unnamed-rating").replace(/\[|\]/g,"_").replace(/^\_+|\_+$/g,""),j=a(this.form||document.body),h=j.data("rating");if(!h||h.call!=a.fn.rating.calls)h={count:0,call:a.fn.rating.calls};var g=h[k];if(g)b=g.data("rating");if(g&&b)b.count++;else{b=a.extend({},c||{},(a.metadata?e.metadata():a.meta?e.data():null)||{},{count:0,stars:[],inputs:[]});b.serial=h.count++;g=a('<span class="star-rating-control"/>');e.before(g);g.addClass("rating-to-be-drawn");if(e.attr("disabled"))b.readOnly=
true;g.append(b.cancel=a('<div class="rating-cancel"><a title="'+b.cancel+'">'+b.cancelValue+"</a></div>").mouseover(function(){a(this).rating("drain");a(this).addClass("star-rating-hover")}).mouseout(function(){a(this).rating("draw");a(this).removeClass("star-rating-hover")}).click(function(){a(this).rating("select")}).data("rating",b))}var f=a('<div class="star-rating rater-'+b.serial+'"><a title="'+(this.title||this.value)+'">'+this.value+"</a></div>");g.append(f);this.id&&f.attr("id",this.id);
this.className&&f.addClass(this.className);if(b.half)b.split=2;if(typeof b.split=="number"&&b.split>0){var i=(a.fn.width?f.width():0)||b.starWidth,l=b.count%b.split;i=Math.floor(i/b.split);f.width(i).find("a").css({"margin-left":"-"+l*i+"px"})}b.readOnly?f.addClass("star-rating-readonly"):f.addClass("star-rating-live").mouseover(function(){a(this).rating("fill");a(this).rating("focus")}).mouseout(function(){a(this).rating("draw");a(this).rating("blur")}).click(function(){a(this).rating("select")});
if(this.checked)b.current=f;e.hide();e.change(function(){a(this).rating("select")});f.data("rating.input",e.data("rating.star",f));b.stars[b.stars.length]=f[0];b.inputs[b.inputs.length]=e[0];b.rater=h[k]=g;b.context=j;e.data("rating",b);g.data("rating",b);f.data("rating",b);j.data("rating",h)});a(".rating-to-be-drawn").rating("draw").removeClass("rating-to-be-drawn");return this};a.extend(a.fn.rating,{calls:0,focus:function(){var c=this.data("rating");if(!c)return this;if(!c.focus)return this;var d=
a(this).data("rating.input")||a(this.tagName=="INPUT"?this:null);c.focus&&c.focus.apply(d[0],[d.val(),a("a",d.data("rating.star"))[0]])},blur:function(){var c=this.data("rating");if(!c)return this;if(!c.blur)return this;var d=a(this).data("rating.input")||a(this.tagName=="INPUT"?this:null);c.blur&&c.blur.apply(d[0],[d.val(),a("a",d.data("rating.star"))[0]])},fill:function(){var c=this.data("rating");if(!c)return this;if(!c.readOnly){this.rating("drain");this.prevAll().andSelf().filter(".rater-"+c.serial).addClass("star-rating-hover")}},
drain:function(){var c=this.data("rating");if(!c)return this;c.readOnly||c.rater.children().filter(".rater-"+c.serial).removeClass("star-rating-on").removeClass("star-rating-hover")},draw:function(){var c=this.data("rating");if(!c)return this;this.rating("drain");if(c.current){c.current.data("rating.input").attr("checked","checked");c.current.prevAll().andSelf().filter(".rater-"+c.serial).addClass("star-rating-on")}else a(c.inputs).removeAttr("checked");c.cancel[c.readOnly||c.required?"hide":"show"]();
this.siblings()[c.readOnly?"addClass":"removeClass"]("star-rating-readonly")},select:function(c,d){var b=this.data("rating");if(!b)return this;if(!b.readOnly){b.current=null;if(typeof c!="undefined"){if(typeof c=="number")return a(b.stars[c]).rating("select",undefined,d);typeof c=="string"&&a.each(b.stars,function(){a(this).data("rating.input").val()==c&&a(this).rating("select",undefined,d)})}else b.current=this[0].tagName=="INPUT"?this.data("rating.star"):this.is(".rater-"+b.serial)?this:null;this.data("rating",
b);this.rating("draw");var e=a(b.current?b.current.data("rating.input"):null);if((d||d==undefined)&&b.callback)b.callback.apply(e[0],[e.val(),a("a",b.current)[0]])}},readOnly:function(c,d){var b=this.data("rating");if(!b)return this;b.readOnly=c||c==undefined?true:false;d?a(b.inputs).attr("disabled","disabled"):a(b.inputs).removeAttr("disabled");this.data("rating",b);this.rating("draw")},disable:function(){this.rating("readOnly",true,true)},enable:function(){this.rating("readOnly",false,false)}});
a.fn.rating.options={cancel:"Cancel Rating",cancelValue:"",split:0,starWidth:16};a(function(){a("input[type=radio].star").rating()})}(jQuery);