function nv_chang_question(a){nv_settimeout_disable("id_weight_"+a,5E3);var b=document.getElementById("id_weight_"+a).options[document.getElementById("id_weight_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=question&changeweight=1&qid="+a+"&new_vid="+b+"&num="+nv_randomPassword(8),"","nv_chang_question_result")}
function nv_chang_question_result(a){a!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_question()}
function nv_save_title(a){var b=document.getElementById("title_"+a),c=document.getElementById("hidden_"+a);if(b.value!=c.value){if(b.value==""){alert(nv_content);b.focus();return false}nv_settimeout_disable("title_"+a,5E3);nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=question&edit=1&qid="+a+"&title="+b.value+"&num="+nv_randomPassword(8),"","nv_save_title_result")}}
function nv_save_title_result(a){a!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_question()}function nv_show_list_question(){document.getElementById("module_show_list")&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=question&qlist=1&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_question(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=question&del=1&qid="+a,"","nv_del_question_result");return false}function nv_del_question_result(a){a=="OK"?nv_show_list_question():alert(nv_is_del_confirm[2]);return false}
function nv_add_question(){var a=document.getElementById("new_title");if(a.value==""){alert(nv_content);a.focus();return false}nv_settimeout_disable("new_title",5E3);nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=question&add=1&title="+a.value+"&num="+nv_randomPassword(8),"","nv_add_question_result")}function nv_add_question_result(a){a=="OK"?nv_show_list_question():alert(nv_content);return false}
function nv_row_del(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del&userid="+a,"","nv_row_del_result");return false}function nv_row_del_result(a){if(a=="OK")window.location.href=window.location.href;else alert(nv_is_del_confirm[2]);return false}
function nv_waiting_row_del(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=user_waiting&del=1&userid="+a,"","nv_waiting_row_del_result");return false}function nv_waiting_row_del_result(a){if(a=="OK")window.location.href=window.location.href;else alert(nv_is_del_confirm[2]);return false}
function nv_chang_status(a){nv_settimeout_disable("change_status_"+a,5E3);nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=setactive&userid="+a+"&num="+nv_randomPassword(8),"","nv_chang_status_res")}function nv_chang_status_res(a){if(a!="OK"){alert(nv_is_change_act_confirm[2]);window.location.href=window.location.href}}
function nv_group_change_status(a){nv_settimeout_disable("select_"+a,5E3);nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=groups_act&group_id="+a+"&num="+nv_randomPassword(8),"","nv_group_change_res")}function nv_group_change_res(a){a=a.split("_");var b=document.getElementById("select_"+a[1]);if(a[0]!="OK"){alert(nv_is_change_act_confirm[2]);b.checked=b.checked==true?false:true;clearTimeout(nv_timer);b.disabled=true}}
function nv_group_del(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=groups_del&group_id="+a,"","nv_group_del_result");return false}function nv_group_del_result(a){if(a.split("_")[0]=="OK")window.location.href=strHref;else alert(nv_is_del_confirm[2]);return false}
function nv_group_search_users(a){var b=document.getElementById("search_query"),c=document.getElementById("search_option").options[document.getElementById("search_option").selectedIndex].value;document.getElementById("is_search").value=1;nv_settimeout_disable("search_click",5E3);b=rawurlencode(b.value);a=rawurldecode(a);nv_ajax("get",a,"search_query="+b+"&search_option="+c,"search_users_result")}
function nv_group_add_user(a,b){var c=document.getElementById("user_"+b);if(confirm(nv_is_add_user_confirm[0])){c.disabled=true;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=groups_add_user&group_id="+a+"&userid="+b,"","nv_group_add_user_res")}else c.checked=false}
function nv_group_add_user_res(a){a=a.split("_");if(a[0]!="OK"){a=document.getElementById("user_"+userid);a.disabled=false;a.checked=false;alert(nv_is_add_user_confirm[2]);return false}else{var b=document.getElementById("count_users_"+a[1]).innerHTML;b=intval(b)+1;document.getElementById("count_users_"+a[1]).innerHTML=b;if(document.getElementById("is_search").value!=0){b=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=groups_search_users&group_id="+a[1];b=rawurlencode(b);
nv_group_search_users(b,"search_users_result")}a=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=groups_users&group_id="+a[1];a=rawurlencode(a);nv_urldecode_ajax(a,"list_users")}}
function nv_group_exclude_user(a,b){var c=document.getElementById("exclude_user_"+b);if(confirm(nv_is_exclude_user_confirm[0])){c.disabled=true;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=groups_exclude_user&group_id="+a+"&userid="+b,"","nv_group_exclude_user_res")}else c.checked=false}
function nv_group_exclude_user_res(a){a=a.split("_");if(a[0]!="OK"){a=document.getElementById("exclude_user_"+userid);a.disabled=false;a.checked=false;alert(nv_is_exclude_user_confirm[2]);return false}else{var b=document.getElementById("count_users_"+a[1]).innerHTML;b=intval(b)-1;document.getElementById("count_users_"+a[1]).innerHTML=b;if(document.getElementById("is_search").value!=0){b=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=groups_search_users&id="+a[1];b=rawurlencode(b);
nv_group_search_users(b,"search_users_result")}a=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=groups_users&group_id="+a[1];a=rawurlencode(a);nv_urldecode_ajax(a,"list_users")}};