var DD_belatedPNG={ns:"DD_belatedPNG",imgSize:{},delay:10,nodesFixed:0,createVmlNameSpace:function(){document.namespaces&&!document.namespaces[this.ns]&&document.namespaces.add(this.ns,"urn:schemas-microsoft-com:vml")},createVmlStyleSheet:function(){var a;a=document.createElement("style");a.setAttribute("media","screen");document.documentElement.firstChild.insertBefore(a,document.documentElement.firstChild.firstChild);if(a.styleSheet)a=a.styleSheet,a.addRule(this.ns+"\\:*","{behavior:url(#default#VML)}"),
a.addRule(this.ns+"\\:shape","position:absolute;"),a.addRule("img."+this.ns+"_sizeFinder","behavior:none; border:none; position:absolute; z-index:-1; top:-10000px; visibility:hidden;"),this.screenStyleSheet=a,a=document.createElement("style"),a.setAttribute("media","print"),document.documentElement.firstChild.insertBefore(a,document.documentElement.firstChild.firstChild),a=a.styleSheet,a.addRule(this.ns+"\\:*","{display: none !important;}"),a.addRule("img."+this.ns+"_sizeFinder","{display: none !important;}")},
readPropertyChange:function(){var a,c,b;a=event.srcElement;if(a.vmlInitiated){(event.propertyName.search("background")!=-1||event.propertyName.search("border")!=-1)&&DD_belatedPNG.applyVML(a);if(event.propertyName=="style.display")for(b in c=a.currentStyle.display=="none"?"none":"block",a.vml)if(a.vml.hasOwnProperty(b))a.vml[b].shape.style.display=c;event.propertyName.search("filter")!=-1&&DD_belatedPNG.vmlOpacity(a)}},vmlOpacity:function(a){if(a.currentStyle.filter.search("lpha")!=-1){var c=a.currentStyle.filter;
c=parseInt(c.substring(c.lastIndexOf("=")+1,c.lastIndexOf(")")),10)/100;a.vml.color.shape.style.filter=a.currentStyle.filter;a.vml.image.fill.opacity=c}},handlePseudoHover:function(a){setTimeout(function(){DD_belatedPNG.applyVML(a)},1)},fix:function(a){if(this.screenStyleSheet){var c;a=a.split(",");for(c=0;c<a.length;c++)this.screenStyleSheet.addRule(a[c],"behavior:expression(DD_belatedPNG.fixPng(this))")}},applyVML:function(a){a.runtimeStyle.cssText="";this.vmlFill(a);this.vmlOffsets(a);this.vmlOpacity(a);
a.isImg&&this.copyImageBorders(a)},attachHandlers:function(a){var c,b,e,d,f;c=this;b={resize:"vmlOffsets",move:"vmlOffsets"};if(a.nodeName=="A")for(d in e={mouseleave:"handlePseudoHover",mouseenter:"handlePseudoHover",focus:"handlePseudoHover",blur:"handlePseudoHover"},e)e.hasOwnProperty(d)&&(b[d]=e[d]);for(f in b)b.hasOwnProperty(f)&&(e=function(){c[b[f]](a)},a.attachEvent("on"+f,e));a.attachEvent("onpropertychange",this.readPropertyChange)},giveLayout:function(a){a.style.zoom=1;if(a.currentStyle.position==
"static")a.style.position="relative"},copyImageBorders:function(a){var c,b;c={borderStyle:!0,borderWidth:!0,borderColor:!0};for(b in c)c.hasOwnProperty(b)&&(a.vml.color.shape.style[b]=a.currentStyle[b])},vmlFill:function(a){if(a.currentStyle){var c,b,e;c=a.currentStyle;for(b in a.vml)if(a.vml.hasOwnProperty(b))a.vml[b].shape.style.zIndex=c.zIndex;a.runtimeStyle.backgroundColor="";a.runtimeStyle.backgroundImage="";b=!0;if(c.backgroundImage!="none"||a.isImg){a.isImg?a.vmlBg=a.src:(a.vmlBg=c.backgroundImage,
a.vmlBg=a.vmlBg.substr(5,a.vmlBg.lastIndexOf('")')-5));e=this;if(!e.imgSize[a.vmlBg])b=document.createElement("img"),e.imgSize[a.vmlBg]=b,b.className=e.ns+"_sizeFinder",b.runtimeStyle.cssText="behavior:none; position:absolute; left:-10000px; top:-10000px; border:none; margin:0; padding:0;",b.attachEvent("onload",function(){this.width=this.offsetWidth;this.height=this.offsetHeight;e.vmlOffsets(a)}),b.src=a.vmlBg,b.removeAttribute("width"),b.removeAttribute("height"),document.body.insertBefore(b,document.body.firstChild);
a.vml.image.fill.src=a.vmlBg;b=!1}a.vml.image.fill.on=!b;a.vml.image.fill.color="none";a.vml.color.shape.style.backgroundColor=c.backgroundColor;a.runtimeStyle.backgroundImage="none";a.runtimeStyle.backgroundColor="transparent"}},vmlOffsets:function(a){var c,b,e,d,f,g;c=a.currentStyle;b={W:a.clientWidth+1,H:a.clientHeight+1,w:this.imgSize[a.vmlBg].width,h:this.imgSize[a.vmlBg].height,L:a.offsetLeft,T:a.offsetTop,bLW:a.clientLeft,bTW:a.clientTop};e=b.L+b.bLW==1?1:0;d=function(a,b,c,d,e,f){a.coordsize=
d+","+e;a.coordorigin=f+","+f;a.path="m0,0l"+d+",0l"+d+","+e+"l0,"+e+" xe";a.style.width=d+"px";a.style.height=e+"px";a.style.left=b+"px";a.style.top=c+"px"};d(a.vml.color.shape,b.L+(a.isImg?0:b.bLW),b.T+(a.isImg?0:b.bTW),b.W-1,b.H-1,0);d(a.vml.image.shape,b.L+b.bLW,b.T+b.bTW,b.W,b.H,1);d={X:0,Y:0};if(a.isImg)d.X=parseInt(c.paddingLeft,10)+1,d.Y=parseInt(c.paddingTop,10)+1;else for(f in d)d.hasOwnProperty(f)&&this.figurePercentage(d,b,f,c["backgroundPosition"+f]);a.vml.image.fill.position=d.X/b.W+
","+d.Y/b.H;f=c.backgroundRepeat;g={T:1,R:b.W+e,B:b.H,L:1+e};c={X:{b1:"L",b2:"R",d:"W"},Y:{b1:"T",b2:"B",d:"H"}};if(f!="repeat"||a.isImg){d={T:d.Y,R:d.X+b.w,B:d.Y+b.h,L:d.X};f.search("repeat-")!=-1&&(f=f.split("repeat-")[1].toUpperCase(),d[c[f].b1]=1,d[c[f].b2]=b[c[f].d]);if(d.B>b.H)d.B=b.H;a.vml.image.shape.style.clip="rect("+d.T+"px "+(d.R+e)+"px "+d.B+"px "+(d.L+e)+"px)"}else a.vml.image.shape.style.clip="rect("+g.T+"px "+g.R+"px "+g.B+"px "+g.L+"px)"},figurePercentage:function(a,c,b,e){var d,
f;f=!0;d=b=="X";switch(e){case "left":case "top":a[b]=0;break;case "center":a[b]=0.5;break;case "right":case "bottom":a[b]=1;break;default:e.search("%")!=-1?a[b]=parseInt(e,10)/100:f=!1}a[b]=Math.ceil(f?c[d?"W":"H"]*a[b]-c[d?"w":"h"]*a[b]:parseInt(e,10));a[b]%2===0&&a[b]++;return a[b]},fixPng:function(a){a.style.behavior="none";var c,b,e,d,f;if(!(a.nodeName=="BODY"||a.nodeName=="TD"||a.nodeName=="TR")){a.isImg=!1;if(a.nodeName=="IMG")if(a.src.toLowerCase().search(/\.png$/)!=-1)a.isImg=!0,a.style.visibility=
"hidden";else return;else if(a.currentStyle.backgroundImage.toLowerCase().search(".png")==-1)return;c=DD_belatedPNG;a.vml={color:{},image:{}};b={shape:{},fill:{}};for(d in a.vml)if(a.vml.hasOwnProperty(d)){for(f in b)b.hasOwnProperty(f)&&(e=c.ns+":"+f,a.vml[d][f]=document.createElement(e));a.vml[d].shape.stroked=!1;a.vml[d].shape.appendChild(a.vml[d].fill);a.parentNode.insertBefore(a.vml[d].shape,a)}a.vml.image.shape.fillcolor="none";a.vml.image.fill.type="tile";a.vml.color.fill.on=!1;c.attachHandlers(a);
c.giveLayout(a);c.giveLayout(a.offsetParent);a.vmlInitiated=!0;c.applyVML(a)}}};try{document.execCommand("BackgroundImageCache",!1,!0)}catch(r){}DD_belatedPNG.createVmlNameSpace();DD_belatedPNG.createVmlStyleSheet();