<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'Predis' => array($vendorDir . '/predis/predis/lib'),
    'OAuth\\Unit' => array($baseDir . '/tests'),
    'OAuth' => array($baseDir . '/src'),
);
